// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Oroshi-zz
/* ============================================================
   FORGE 90 — Comprehensive food database + food-group tree
   Values per 100 g (or per 100 ml where noted, or per unit when a unit is given),
   approximated from USDA FoodData Central / typical US labels. Any food can be edited in the app.
   ============================================================ */

/* ---------- food groups: category → subcategory ---------- */
const FOOD_CATS = [
  { id: 'meat', name: 'Meat & poultry', icon: '🍗', subs: [['chicken_white', 'Chicken — breast & white meat'], ['chicken_dark', 'Chicken — thighs, drumsticks & wings'], ['turkey', 'Turkey'], ['beef_lean', 'Beef — lean cuts & 90%+ ground'], ['beef_fatty', 'Beef — fattier cuts & 80/20 ground'], ['pork', 'Pork'], ['lamb', 'Lamb, bison, duck & game'], ['deli', 'Deli meats'], ['sausage', 'Bacon & sausages'], ['jerky', 'Jerky & meat sticks']] },
  { id: 'seafood', name: 'Seafood', icon: '🐟', subs: [['raw_fish', 'Sushi & poke fish'], ['canned_tuna', 'Canned tuna'], ['canned_fish', 'Other canned fish'], ['fatty_fish', 'Cooked fatty fish (salmon, trout…)'], ['white_fish', 'Cooked white fish (cod, tilapia…)'], ['shellfish', 'Shrimp & shellfish']] },
  { id: 'eggs', name: 'Eggs', icon: '🥚', subs: [['whole_eggs', 'Whole eggs'], ['egg_whites', 'Egg whites']] },
  { id: 'dairy', name: 'Dairy & alternatives', icon: '🥛', subs: [['milk', 'Milk & milk drinks'], ['milk_alt', 'Plant milks'], ['yogurt', 'Yogurt & skyr'], ['cottage', 'Cottage cheese & ricotta'], ['cheese', 'Hard & shredded cheese'], ['soft_cheese', 'Soft & cream cheese'], ['butter_cream', 'Butter, cream & sour cream']] },
  { id: 'plant', name: 'Plant proteins', icon: '🌱', subs: [['soy', 'Tofu, tempeh & edamame'], ['seitan', 'Seitan & meat alternatives']] },
  { id: 'legumes', name: 'Beans & legumes', icon: '🫘', subs: [['beans', 'Beans'], ['lentils', 'Lentils, chickpeas & hummus']] },
  { id: 'grains', name: 'Grains & starches', icon: '🍚', subs: [['rice', 'Rice'], ['ancient', 'Quinoa & other grains'], ['oats', 'Oats & hot cereal'], ['cereal', 'Cold cereal & granola'], ['bread', 'Bread, bagels & buns'], ['wraps', 'Tortillas & wraps'], ['pasta', 'Pasta & noodles'], ['potatoes', 'Potatoes & sweet potatoes'], ['crackers', 'Crackers, rice cakes & popcorn'], ['baking', 'Pancake mix, flour & waffles']] },
  { id: 'fruit', name: 'Fruit', icon: '🍎', subs: [['berries', 'Berries'], ['citrus', 'Citrus'], ['tropical', 'Tropical fruit'], ['tree_fruit', 'Apples, pears & stone fruit'], ['melon', 'Melons & grapes'], ['dried_fruit', 'Dried fruit'], ['avocado', 'Avocado & guacamole']] },
  { id: 'veg', name: 'Vegetables', icon: '🥦', subs: [['leafy', 'Leafy greens'], ['cruciferous', 'Broccoli, cauliflower & cabbage'], ['alliums', 'Peppers, onions & garlic'], ['root_veg', 'Carrots & root vegetables'], ['squash', 'Squash & zucchini'], ['tomatoes', 'Tomatoes & cucumbers'], ['other_veg', 'Other vegetables (beans, peas, corn, mushrooms…)']] },
  { id: 'nuts', name: 'Nuts & seeds', icon: '🥜', subs: [['peanuts', 'Peanuts & peanut butter'], ['tree_nuts', 'Tree nuts & nut butters'], ['seeds', 'Seeds']] },
  { id: 'fats', name: 'Oils & dressings', icon: '🫒', subs: [['oils', 'Cooking oils'], ['dressings', 'Mayo & dressings'], ['olives', 'Olives']] },
  { id: 'supps', name: 'Protein products', icon: '🥤', subs: [['whey', 'Whey protein'], ['other_protein', 'Casein, plant & collagen protein'], ['bars', 'Protein & snack bars'], ['rtd', 'Ready-to-drink protein shakes']] },
  { id: 'pantry', name: 'Sauces & pantry', icon: '🧂', subs: [['sauces', 'Sauces'], ['condiments', 'Condiments & pickles'], ['spices', 'Spices, broth & pantry basics']] },
  { id: 'prepared', name: 'Prepared & takeout', icon: '🍱', subs: [['frozen_meals', 'Frozen meals & convenience foods'], ['takeout', 'Restaurant & takeout'], ['soups', 'Soups & chili']] },
  { id: 'sweets', name: 'Sweets & snacks', icon: '🍫', subs: [['sweeteners', 'Honey, syrups & sugar'], ['sweets', 'Chocolate, ice cream & candy'], ['chips', 'Chips & salty snacks']] },
  { id: 'drinks', name: 'Drinks', icon: '🧃', subs: [['juice', 'Juice & sports drinks'], ['zero_drinks', 'Coffee, tea & zero-calorie drinks'], ['soda', 'Regular soda & energy drinks'], ['alcohol', 'Beer & wine']] }
];
const SUB_CAT = {}; const SUB_LABEL = {};
FOOD_CATS.forEach(c => c.subs.forEach(([id, l]) => { SUB_CAT[id] = c.id; SUB_LABEL[id] = l; }));
const AISLES = ['Meat & Seafood', 'Dairy & Eggs', 'Produce', 'Grains & Bread', 'Frozen', 'Pantry', 'Snacks', 'Beverages', 'Deli & Prepared'];

// Subgroups for the original foods
const BASE_SUB = {
  chicken_breast: 'chicken_white', chicken_thigh: 'chicken_dark', turkey_937: 'turkey', beef_937: 'beef_lean', sirloin: 'beef_lean', pork_tenderloin: 'pork', canadian_bacon: 'pork',
  deli_turkey: 'deli', jerky: 'jerky', ahi: 'raw_fish', salmon: 'raw_fish', tuna_can: 'canned_tuna', salmon_fillet: 'fatty_fish', shrimp: 'shellfish',
  egg: 'whole_eggs', egg_whites: 'egg_whites', greek_yogurt: 'yogurt', cottage: 'cottage', fairlife: 'milk', cheese_shred: 'cheese', feta: 'soft_cheese', parmesan: 'cheese', string_cheese: 'cheese',
  whey: 'whey', pb2: 'peanuts', protein_bar: 'bars', oats: 'oats', granola: 'cereal', rice: 'rice', sushi_rice: 'rice', quinoa: 'ancient', rice_cake: 'crackers', protein_pasta: 'pasta',
  kodiak: 'baking', tortilla_lg: 'wraps', tortilla_sm: 'wraps', bread: 'bread', english_muffin: 'bread', sweet_potato: 'potatoes', potato: 'potatoes',
  black_beans: 'beans', kidney_beans: 'beans', edamame: 'soy', tofu: 'soy', corn: 'other_veg', banana: 'tropical', apple: 'tree_fruit', berries: 'berries', pineapple: 'tropical', avocado: 'avocado',
  honey: 'sweeteners', syrup_sf: 'sweeteners', teriyaki: 'sauces', marinara: 'sauces', crushed_tomatoes: 'sauces', salsa: 'sauces', ketchup: 'condiments', cornstarch: 'spices',
  soy_sauce: 'condiments', sriracha: 'condiments', cocoa: 'spices', pickles: 'condiments', nori: 'spices', olive_oil: 'oils', sesame_oil: 'oils', light_mayo: 'dressings', pb: 'peanuts', chia: 'seeds',
  spinach: 'leafy', bell_pepper: 'alliums', onion: 'alliums', broccoli: 'cruciferous', stir_fry_veg: 'other_veg', green_beans: 'other_veg', asparagus: 'other_veg', romaine: 'leafy',
  cucumber: 'tomatoes', cherry_tomato: 'tomatoes', celery: 'other_veg', carrots: 'root_veg'
};
// Old (v3) subgroup → new subgroups, for migrating saved preferences
const PREF_MIGRATE = {
  chicken: ['chicken_white', 'chicken_dark'], beef: ['beef_lean', 'beef_fatty'], deli: ['deli', 'jerky', 'sausage'], cooked_fish: ['fatty_fish', 'white_fish', 'canned_fish'],
  milk: ['milk', 'milk_alt'], cheese: ['cheese', 'soft_cheese'], rice: ['rice', 'ancient', 'crackers'], oats: ['oats', 'cereal'], bread: ['bread', 'wraps', 'baking'],
  fruit: ['tree_fruit', 'berries', 'citrus', 'tropical', 'melon', 'dried_fruit', 'avocado'], veg: ['other_veg', 'leafy', 'cruciferous', 'alliums', 'root_veg', 'squash', 'tomatoes'],
  sauces: ['sauces', 'condiments', 'spices'], oils: ['oils', 'dressings', 'olives'], soy: ['soy'], beans: ['beans', 'lentils'], 'cat:pantry': ['cat:pantry', 'cat:fats', 'cat:sweets'], 'cat:legumes': ['cat:legumes', 'cat:plant']
};
// Per the project brief: fish only as sushi, poke and canned tuna
const DEFAULT_FOOD_PREFS = { fatty_fish: false, white_fish: false, canned_fish: false, shellfish: false };

/* ---------- default portion-scaling role and aisle by subgroup ---------- */
const P_SUBS = ['chicken_white', 'chicken_dark', 'turkey', 'beef_lean', 'beef_fatty', 'pork', 'lamb', 'deli', 'jerky', 'raw_fish', 'canned_tuna', 'canned_fish', 'fatty_fish', 'white_fish', 'shellfish',
  'whole_eggs', 'egg_whites', 'yogurt', 'cottage', 'soy', 'seitan', 'whey', 'other_protein', 'rtd'];
const F_SUBS = ['sausage', 'cheese', 'soft_cheese', 'butter_cream', 'peanuts', 'tree_nuts', 'seeds', 'oils', 'dressings', 'olives', 'avocado'];
const V_SUBS = ['leafy', 'cruciferous', 'alliums', 'root_veg', 'squash', 'tomatoes', 'other_veg', 'condiments', 'spices', 'zero_drinks'];
const CAT_AISLE = { meat: 'Meat & Seafood', seafood: 'Meat & Seafood', eggs: 'Dairy & Eggs', dairy: 'Dairy & Eggs', plant: 'Produce', legumes: 'Pantry', grains: 'Grains & Bread', fruit: 'Produce', veg: 'Produce', nuts: 'Pantry', fats: 'Pantry', supps: 'Pantry', pantry: 'Pantry', sweets: 'Snacks', drinks: 'Beverages', prepared: 'Frozen' };
const SUB_AISLE = { takeout: 'Deli & Prepared', soups: 'Pantry' };
function defaultRole(sub, k, p, c, f) { if (P_SUBS.includes(sub)) return 'P'; if (F_SUBS.includes(sub)) return 'F'; if (V_SUBS.includes(sub) && k < 90) return 'V'; if (k < 25) return 'V'; return 'C'; }

/* ---------- the list ----------
   [id, name, sub, kcal, protein, carbs, fat, options]
   options: { u: 'unit name', g: grams per unit } → values are per unit · { ml: true } → per 100 ml · { a: aisle } · { r: role } */
const MORE_FOODS = [
  // Chicken
  ['chicken_tenders', 'Chicken tenderloins, raw', 'chicken_white', 112, 23, 0, 1.7],
  ['chicken_breast_cooked', 'Chicken breast, cooked', 'chicken_white', 165, 31, 0, 3.6],
  ['rotisserie_chicken', 'Rotisserie chicken meat, no skin', 'chicken_white', 170, 26, 0, 7],
  ['canned_chicken', 'Canned chicken breast, drained', 'chicken_white', 107, 21, 0, 2, { a: 'Pantry' }],
  ['ground_chicken', 'Ground chicken, raw', 'chicken_dark', 143, 17.4, 0, 8.1],
  ['chicken_drumstick', 'Chicken drumsticks, skinless, raw', 'chicken_dark', 116, 19.4, 0, 3.7],
  ['chicken_thigh_skin', 'Chicken thighs, bone-in with skin, raw', 'chicken_dark', 221, 15.5, 0, 17.3],
  ['chicken_wings', 'Chicken wings, raw', 'chicken_dark', 191, 17.5, 0, 12.8],
  // Turkey
  ['turkey_breast', 'Turkey breast cutlets, raw', 'turkey', 114, 23.7, 0, 1.5],
  ['ground_turkey_99', 'Ground turkey 99% lean, raw', 'turkey', 106, 23, 0, 1.3],
  ['ground_turkey_85', 'Ground turkey 85/15, raw', 'turkey', 212, 18.6, 0, 15],
  // Beef
  ['beef_955', 'Ground beef 95/5, raw', 'beef_lean', 137, 21.4, 0, 5],
  ['beef_9010', 'Ground beef 90/10, raw', 'beef_lean', 176, 20, 0, 10],
  ['eye_round', 'Eye of round steak, raw', 'beef_lean', 125, 23.4, 0, 3.3],
  ['flank_steak', 'Flank steak, raw', 'beef_lean', 155, 21.2, 0, 7.2],
  ['beef_tenderloin', 'Beef tenderloin (filet), raw', 'beef_lean', 158, 21.2, 0, 7.6],
  ['beef_8020', 'Ground beef 80/20, raw', 'beef_fatty', 254, 17.2, 0, 20],
  ['ribeye', 'Ribeye steak, raw', 'beef_fatty', 280, 18.5, 0, 22.8],
  ['ny_strip', 'NY strip steak, raw', 'beef_fatty', 216, 20.7, 0, 14.6],
  ['chuck_roast', 'Chuck roast / stew meat, raw', 'beef_fatty', 190, 19, 0, 12.3],
  ['brisket', 'Beef brisket, raw', 'beef_fatty', 250, 17.4, 0, 19.5],
  // Pork
  ['pork_chop', 'Pork loin chop, boneless, raw', 'pork', 150, 21.5, 0, 6.8],
  ['pork_shoulder', 'Pork shoulder (butt), raw', 'pork', 230, 17, 0, 17.8],
  ['ground_pork', 'Ground pork, raw', 'pork', 263, 16.9, 0, 21.2],
  ['pork_ribs', 'Pork spare ribs, raw', 'pork', 277, 15.5, 0, 23.4],
  // Lamb & game
  ['lamb_leg', 'Leg of lamb, raw', 'lamb', 160, 20.5, 0, 8.5],
  ['lamb_ground', 'Ground lamb, raw', 'lamb', 282, 16.6, 0, 23.4],
  ['bison_ground', 'Ground bison 90/10, raw', 'lamb', 168, 19.4, 0, 9.7],
  ['venison', 'Venison, raw', 'lamb', 120, 23, 0, 2.4],
  // Deli
  ['deli_ham', 'Deli ham', 'deli', 106, 17.5, 1.8, 3],
  ['deli_chicken', 'Deli chicken breast', 'deli', 88, 17.6, 1.8, 1],
  ['roast_beef_deli', 'Deli roast beef', 'deli', 115, 18.6, 0.6, 4.3],
  ['salami', 'Salami', 'deli', 407, 22.6, 1.9, 33.7],
  // Bacon & sausages
  ['bacon', 'Bacon, cooked', 'sausage', 43, 3, 0.1, 3.3, { u: 'slice', g: 8 }],
  ['turkey_bacon', 'Turkey bacon', 'sausage', 218, 17, 3, 15],
  ['turkey_sausage', 'Turkey breakfast sausage', 'sausage', 196, 16, 1, 14],
  ['chicken_sausage', 'Chicken sausage, fully cooked', 'sausage', 170, 16, 3, 10],
  ['pork_sausage', 'Pork breakfast sausage, raw', 'sausage', 325, 15, 1, 29],
  ['italian_sausage', 'Italian sausage, raw', 'sausage', 300, 14.3, 1.4, 26.6],
  ['hot_dog', 'Beef hot dog', 'sausage', 145, 5, 1.2, 13.2, { u: 'hot dog', g: 45 }],
  ['pepperoni', 'Pepperoni', 'sausage', 504, 19.3, 1.2, 46.3],
  // Jerky
  ['turkey_jerky', 'Turkey jerky', 'jerky', 282, 42, 18, 3.5, { a: 'Snacks' }],
  ['meat_stick', 'Beef meat stick', 'jerky', 100, 6, 1, 8, { u: 'stick', g: 28, a: 'Snacks' }],
  // Seafood
  ['yellowtail', 'Sushi-grade yellowtail (hamachi)', 'raw_fish', 146, 23.1, 0, 5.2],
  ['imitation_crab', 'Imitation crab (surimi)', 'raw_fish', 95, 7.6, 15, 0.5],
  ['tuna_albacore', 'Canned albacore tuna in water, drained', 'canned_tuna', 128, 23.6, 0, 3, { a: 'Pantry' }],
  ['tuna_oil', 'Canned tuna in oil, drained', 'canned_tuna', 198, 29.1, 0, 8.2, { a: 'Pantry' }],
  ['canned_salmon', 'Canned salmon, drained', 'canned_fish', 136, 23, 0, 4.9, { a: 'Pantry' }],
  ['sardines', 'Sardines in oil, drained', 'canned_fish', 208, 24.6, 0, 11.5, { a: 'Pantry' }],
  ['smoked_salmon', 'Smoked salmon (lox)', 'fatty_fish', 117, 18.3, 0, 4.3],
  ['trout', 'Rainbow trout, raw', 'fatty_fish', 141, 20.8, 0, 5.8],
  ['mackerel', 'Atlantic mackerel, raw', 'fatty_fish', 205, 18.6, 0, 13.9],
  ['swordfish', 'Swordfish, raw', 'fatty_fish', 144, 19.8, 0, 6.7],
  ['cod', 'Cod, raw', 'white_fish', 82, 17.8, 0, 0.7],
  ['tilapia', 'Tilapia, raw', 'white_fish', 96, 20.1, 0, 1.7],
  ['halibut', 'Halibut, raw', 'white_fish', 91, 18.6, 0, 1.3],
  ['mahi', 'Mahi-mahi, raw', 'white_fish', 85, 18.5, 0, 0.7],
  ['scallops', 'Sea scallops, raw', 'shellfish', 69, 12.1, 3.2, 0.5],
  ['crab', 'Crab meat, cooked', 'shellfish', 83, 17.9, 0, 0.7],
  ['lobster', 'Lobster meat, cooked', 'shellfish', 89, 19, 0, 0.9],
  ['mussels', 'Mussels, raw', 'shellfish', 86, 11.9, 3.7, 2.2],
  ['oysters', 'Oysters, raw', 'shellfish', 81, 9.5, 5, 2.3],
  // Eggs
  ['egg_boiled', 'Hard-boiled egg, peeled', 'whole_eggs', 78, 6.3, 0.6, 5.3, { u: 'egg', g: 50 }],
  ['egg_jumbo', 'Jumbo eggs', 'whole_eggs', 90, 7.9, 0.5, 6, { u: 'egg', g: 63 }],
  ['egg_substitute', 'Egg substitute (Egg Beaters)', 'egg_whites', 48, 10, 2, 0, { ml: true }],
  // Dairy
  ['milk_whole', 'Whole milk', 'milk', 61, 3.2, 4.8, 3.3, { ml: true }],
  ['milk_2', '2% milk', 'milk', 50, 3.3, 4.8, 2, { ml: true }],
  ['milk_skim', 'Skim milk', 'milk', 34, 3.4, 5, 0.1, { ml: true }],
  ['choc_milk', 'Low-fat chocolate milk', 'milk', 66, 3.3, 10.4, 1, { ml: true }],
  ['kefir', 'Low-fat kefir', 'milk', 41, 3.8, 4.5, 1, { ml: true }],
  ['almond_milk', 'Unsweetened almond milk', 'milk_alt', 15, 0.6, 0.3, 1.2, { ml: true }],
  ['oat_milk', 'Oat milk', 'milk_alt', 50, 1.3, 6.7, 2.1, { ml: true }],
  ['soy_milk', 'Unsweetened soy milk', 'milk_alt', 33, 2.9, 1.2, 1.8, { ml: true }],
  ['greek_yogurt_2', '2% Greek yogurt', 'yogurt', 73, 9.9, 3.9, 1.9],
  ['greek_yogurt_whole', 'Whole-milk Greek yogurt', 'yogurt', 97, 9, 3.9, 5],
  ['greek_yogurt_light', 'Flavored light Greek yogurt', 'yogurt', 67, 10, 4.7, 0],
  ['skyr', 'Plain skyr', 'yogurt', 63, 11, 4, 0.2],
  ['yogurt_plain', 'Plain low-fat yogurt', 'yogurt', 63, 5.3, 7, 1.6],
  ['cottage_ff', 'Fat-free cottage cheese', 'cottage', 72, 10.3, 6.7, 0.3],
  ['cottage_4', '4% cottage cheese', 'cottage', 98, 11.1, 3.4, 4.3],
  ['ricotta_ps', 'Part-skim ricotta', 'cottage', 138, 11.4, 5.1, 7.9],
  ['cheddar', 'Cheddar cheese', 'cheese', 403, 24.9, 1.3, 33.1],
  ['mozzarella_ps', 'Mozzarella, part-skim', 'cheese', 254, 24.3, 2.8, 15.9],
  ['swiss', 'Swiss cheese', 'cheese', 380, 27, 1.5, 27.8],
  ['provolone', 'Provolone', 'cheese', 351, 25.6, 2.1, 26.6],
  ['american_cheese', 'American cheese slice', 'cheese', 60, 3, 2, 4.5, { u: 'slice', g: 19 }],
  ['cottage_cheese_crumbles', 'Cotija / queso fresco', 'cheese', 299, 18, 3, 24],
  ['cream_cheese', 'Cream cheese', 'soft_cheese', 342, 5.9, 4.1, 34.2],
  ['cream_cheese_light', 'Light cream cheese (Neufchâtel)', 'soft_cheese', 253, 9.2, 3.6, 22.8],
  ['goat_cheese', 'Goat cheese, soft', 'soft_cheese', 264, 18.5, 0.9, 21.1],
  ['brie', 'Brie', 'soft_cheese', 334, 20.8, 0.5, 27.7],
  ['butter', 'Butter', 'butter_cream', 717, 0.9, 0.1, 81.1],
  ['ghee', 'Ghee', 'butter_cream', 876, 0, 0, 99.5],
  ['heavy_cream', 'Heavy cream', 'butter_cream', 340, 2.8, 2.7, 36, { ml: true }],
  ['half_half', 'Half-and-half', 'butter_cream', 131, 3.1, 4.3, 11.5, { ml: true }],
  ['sour_cream', 'Sour cream', 'butter_cream', 198, 2.4, 4.6, 19.4],
  ['sour_cream_light', 'Light sour cream', 'butter_cream', 136, 3.5, 7.1, 10.6],
  // Plant proteins
  ['silken_tofu', 'Silken tofu', 'soy', 55, 4.8, 2.9, 2.7],
  ['tempeh', 'Tempeh', 'soy', 192, 20.3, 7.6, 10.8],
  ['seitan', 'Seitan', 'seitan', 120, 24, 4, 1.5],
  ['plant_burger', 'Plant-based burger patty', 'seitan', 212, 16.8, 8, 12.4, { a: 'Frozen' }],
  ['meatless_crumbles', 'Meatless crumbles', 'seitan', 145, 16, 5.5, 5.5, { a: 'Frozen' }],
  // Beans & legumes
  ['pinto_beans', 'Pinto beans, cooked', 'beans', 143, 9, 26.2, 0.7],
  ['white_beans', 'White beans (cannellini/great northern), cooked', 'beans', 118, 8.3, 21.1, 0.4],
  ['refried_beans', 'Fat-free refried beans', 'beans', 77, 4.6, 13.8, 0],
  ['baked_beans', 'Baked beans, canned', 'beans', 94, 4.8, 21.1, 0.4],
  ['lentils', 'Lentils, cooked', 'lentils', 116, 9, 20.1, 0.4],
  ['chickpeas', 'Chickpeas, cooked', 'lentils', 164, 8.9, 27.4, 2.6],
  ['split_peas', 'Split peas, cooked', 'lentils', 118, 8.3, 21.1, 0.4],
  ['hummus', 'Hummus', 'lentils', 166, 7.9, 14.3, 9.6, { a: 'Produce' }],
  // Rice & grains
  ['brown_rice', 'Brown rice, cooked', 'rice', 123, 2.7, 25.6, 1, { dry: 0.33, dryName: 'Brown rice, uncooked' }],
  ['wild_rice', 'Wild rice, cooked', 'rice', 101, 4, 21.3, 0.3, { dry: 0.33, dryName: 'Wild rice, uncooked' }],
  ['microwave_rice', 'Microwave rice cup, cooked', 'rice', 140, 2.8, 30, 1],
  ['couscous', 'Couscous, cooked', 'ancient', 112, 3.8, 23.2, 0.2],
  ['farro', 'Farro, cooked', 'ancient', 125, 4.5, 26, 0.8],
  ['barley', 'Pearl barley, cooked', 'ancient', 123, 2.3, 28.2, 0.4],
  ['bulgur', 'Bulgur, cooked', 'ancient', 83, 3.1, 18.6, 0.2],
  ['steel_oats', 'Steel-cut oats, dry', 'oats', 375, 12.5, 67, 6.3],
  ['instant_oats', 'Instant oatmeal packet, plain', 'oats', 100, 3.7, 19, 1.7, { u: 'packet', g: 28 }],
  ['cream_of_rice', 'Cream of rice, dry', 'oats', 360, 6, 80, 0.5],
  ['oat_cereal', 'Toasted oat cereal (Cheerios-style)', 'cereal', 359, 12.8, 74, 6.4],
  ['bran_flakes', 'Bran flakes', 'cereal', 325, 10, 80, 2.5],
  ['corn_flakes', 'Corn flakes', 'cereal', 357, 7.5, 84, 0.4],
  ['protein_cereal', 'High-protein cereal', 'cereal', 378, 35, 40, 19],
  ['white_bread', 'White bread', 'bread', 74, 2.5, 13.8, 1, { u: 'slice', g: 28 }],
  ['sourdough', 'Sourdough bread', 'bread', 120, 4.8, 23, 0.8, { u: 'slice', g: 45 }],
  ['ezekiel', 'Sprouted-grain bread (Ezekiel-style)', 'bread', 80, 5, 15, 0.5, { u: 'slice', g: 34 }],
  ['bagel', 'Plain bagel', 'bread', 257, 10, 50.5, 1.6, { u: 'bagel', g: 100 }],
  ['bagel_thin', 'Bagel thin', 'bread', 110, 5, 23, 0.5, { u: 'bagel thin', g: 45 }],
  ['burger_bun', 'Hamburger bun', 'bread', 140, 4.5, 26, 2, { u: 'bun', g: 50 }],
  ['ww_pita', 'Whole-wheat pita', 'bread', 170, 6.3, 35.2, 1.7, { u: 'pita', g: 64 }],
  ['naan', 'Naan', 'bread', 262, 8.7, 45, 5.1, { u: 'naan', g: 90 }],
  ['flour_tortilla', 'Flour tortilla, 10-in', 'wraps', 220, 6, 36, 5.5, { u: 'tortilla', g: 72 }],
  ['corn_tortilla', 'Corn tortilla, 6-in', 'wraps', 57, 1.5, 11.6, 0.8, { u: 'tortilla', g: 26 }],
  ['lowcarb_tortilla', 'Low-carb high-fiber tortilla', 'wraps', 70, 5, 19, 2.5, { u: 'tortilla', g: 45 }],
  ['pasta_dry', 'Pasta, dry', 'pasta', 371, 13, 74.7, 1.5],
  ['ww_pasta', 'Whole-wheat pasta, dry', 'pasta', 348, 14.6, 71, 2.5],
  ['chickpea_pasta', 'Chickpea pasta, dry', 'pasta', 339, 19.6, 57, 6.3],
  ['egg_noodles', 'Egg noodles, dry', 'pasta', 384, 14.2, 71.3, 4.4],
  ['rice_noodles', 'Rice noodles, dry', 'pasta', 364, 6, 80, 0.6],
  ['soba', 'Soba noodles, dry', 'pasta', 336, 14.4, 74.6, 0.7],
  ['shirataki', 'Shirataki noodles', 'pasta', 9, 0, 3, 0, { r: 'V' }],
  ['red_potato', 'Red potatoes', 'potatoes', 70, 1.9, 15.9, 0.1],
  ['yukon_potato', 'Yukon gold potatoes', 'potatoes', 77, 2, 17.5, 0.1],
  ['frozen_fries', 'Frozen fries, oven-baked', 'potatoes', 150, 2.4, 24, 5, { a: 'Frozen' }],
  ['hash_browns', 'Frozen hash browns, plain', 'potatoes', 82, 2, 17.3, 0.6, { a: 'Frozen' }],
  ['popcorn', 'Popcorn, air-popped', 'crackers', 387, 12.9, 77.8, 4.5, { a: 'Snacks' }],
  ['pretzels', 'Pretzels', 'crackers', 380, 10.3, 79.8, 2.6, { a: 'Snacks' }],
  ['saltines', 'Saltine crackers', 'crackers', 421, 9.5, 74, 8.9, { a: 'Snacks' }],
  ['wg_crackers', 'Whole-grain crackers', 'crackers', 440, 9, 69, 14, { a: 'Snacks' }],
  ['graham', 'Graham crackers', 'crackers', 430, 6.7, 77.7, 10.6, { a: 'Snacks' }],
  ['flour_ap', 'All-purpose flour', 'baking', 364, 10.3, 76.3, 1, { a: 'Pantry' }],
  ['almond_flour', 'Almond flour', 'baking', 571, 21.4, 21.4, 50, { a: 'Pantry' }],
  ['panko', 'Panko breadcrumbs', 'baking', 395, 13, 80, 3, { a: 'Pantry' }],
  ['frozen_waffle', 'Frozen whole-grain waffle', 'baking', 94, 3, 15, 2.5, { u: 'waffle', g: 35, a: 'Frozen' }],
  // Fruit
  ['strawberries', 'Strawberries', 'berries', 32, 0.7, 7.7, 0.3],
  ['blueberries', 'Blueberries', 'berries', 57, 0.7, 14.5, 0.3],
  ['raspberries', 'Raspberries', 'berries', 52, 1.2, 11.9, 0.7],
  ['blackberries', 'Blackberries', 'berries', 43, 1.4, 9.6, 0.5],
  ['orange', 'Orange, medium', 'citrus', 62, 1.2, 15.4, 0.2, { u: 'orange', g: 131 }],
  ['clementine', 'Clementine', 'citrus', 35, 0.6, 8.9, 0.1, { u: 'clementine', g: 74 }],
  ['grapefruit', 'Grapefruit half', 'citrus', 52, 0.9, 13, 0.2, { u: 'half', g: 123 }],
  ['lemon_juice', 'Lemon or lime juice', 'citrus', 22, 0.4, 6.9, 0.2, { ml: true, r: 'V' }],
  ['mango', 'Mango', 'tropical', 60, 0.8, 15, 0.4],
  ['papaya', 'Papaya', 'tropical', 43, 0.5, 10.8, 0.3],
  ['kiwi', 'Kiwi', 'tropical', 46, 0.8, 11, 0.4, { u: 'kiwi', g: 75 }],
  ['coconut_shredded', 'Unsweetened shredded coconut', 'tropical', 660, 6.9, 23.7, 64.5, { r: 'F', a: 'Pantry' }],
  ['pear', 'Pear, medium', 'tree_fruit', 101, 0.6, 27, 0.3, { u: 'pear', g: 178 }],
  ['peach', 'Peach, medium', 'tree_fruit', 59, 1.4, 14.3, 0.4, { u: 'peach', g: 150 }],
  ['cherries', 'Cherries', 'tree_fruit', 63, 1.1, 16, 0.2],
  ['applesauce', 'Unsweetened applesauce', 'tree_fruit', 42, 0.2, 11.3, 0.1, { a: 'Pantry' }],
  ['watermelon', 'Watermelon', 'melon', 30, 0.6, 7.6, 0.2],
  ['cantaloupe', 'Cantaloupe', 'melon', 34, 0.8, 8.2, 0.2],
  ['honeydew', 'Honeydew', 'melon', 36, 0.5, 9.1, 0.1],
  ['grapes', 'Grapes', 'melon', 69, 0.7, 18.1, 0.2],
  ['raisins', 'Raisins', 'dried_fruit', 299, 3.1, 79.2, 0.5, { a: 'Pantry' }],
  ['dates', 'Medjool dates', 'dried_fruit', 66, 0.4, 18, 0, { u: 'date', g: 24, a: 'Pantry' }],
  ['dried_cranberries', 'Dried cranberries', 'dried_fruit', 308, 0.1, 82.4, 1.4, { a: 'Pantry' }],
  ['prunes', 'Prunes', 'dried_fruit', 240, 2.2, 63.9, 0.4, { a: 'Pantry' }],
  ['guacamole', 'Guacamole', 'avocado', 150, 2, 8.5, 13],
  // Vegetables
  ['kale', 'Kale', 'leafy', 35, 2.9, 4.4, 1.5],
  ['spring_mix', 'Spring mix salad greens', 'leafy', 20, 1.8, 3.3, 0.3],
  ['arugula', 'Arugula', 'leafy', 25, 2.6, 3.7, 0.7],
  ['iceberg', 'Iceberg lettuce', 'leafy', 14, 0.9, 3, 0.1],
  ['cauliflower', 'Cauliflower', 'cruciferous', 25, 1.9, 5, 0.3],
  ['cauli_rice', 'Riced cauliflower, frozen', 'cruciferous', 25, 1.9, 5, 0.3, { a: 'Frozen' }],
  ['brussels', 'Brussels sprouts', 'cruciferous', 43, 3.4, 9, 0.3],
  ['cabbage', 'Cabbage / coleslaw mix', 'cruciferous', 25, 1.3, 5.8, 0.1],
  ['bok_choy', 'Bok choy', 'cruciferous', 13, 1.5, 2.2, 0.2],
  ['broccoli_frozen', 'Broccoli florets, frozen', 'cruciferous', 28, 3.1, 5.4, 0.3, { a: 'Frozen' }],
  ['jalapeno', 'Jalapeño', 'alliums', 29, 0.9, 6.5, 0.4],
  ['green_onion', 'Green onions', 'alliums', 32, 1.8, 7.3, 0.2],
  ['garlic', 'Garlic', 'alliums', 149, 6.4, 33, 0.5, { r: 'V' }],
  ['red_onion', 'Red onion', 'alliums', 40, 1.1, 9.3, 0.1],
  ['beets', 'Beets', 'root_veg', 43, 1.6, 9.6, 0.2],
  ['parsnip', 'Parsnips', 'root_veg', 75, 1.2, 18, 0.3, { r: 'C' }],
  ['radish', 'Radishes', 'root_veg', 16, 0.7, 3.4, 0.1],
  ['zucchini', 'Zucchini', 'squash', 17, 1.2, 3.1, 0.3],
  ['yellow_squash', 'Yellow squash', 'squash', 16, 1.2, 3.4, 0.2],
  ['butternut', 'Butternut squash', 'squash', 45, 1, 11.7, 0.1],
  ['spaghetti_squash', 'Spaghetti squash', 'squash', 31, 0.6, 7, 0.6],
  ['pumpkin_puree', 'Pumpkin purée, canned', 'squash', 34, 1.1, 8.1, 0.3, { a: 'Pantry' }],
  ['tomato', 'Tomatoes', 'tomatoes', 18, 0.9, 3.9, 0.2],
  ['mushrooms', 'White mushrooms', 'other_veg', 22, 3.1, 3.3, 0.3],
  ['peas', 'Green peas, frozen', 'other_veg', 77, 5.4, 13.6, 0.4, { a: 'Frozen', r: 'C' }],
  ['snap_peas', 'Sugar snap peas', 'other_veg', 42, 2.8, 7.6, 0.2],
  ['eggplant', 'Eggplant', 'other_veg', 25, 1, 5.9, 0.2],
  ['mixed_veg', 'Mixed vegetables, frozen', 'other_veg', 65, 3.3, 13.5, 0.5, { a: 'Frozen', r: 'C' }],
  ['artichoke', 'Artichoke hearts, canned', 'other_veg', 47, 3.3, 10.5, 0.2, { a: 'Pantry' }],
  // Nuts & seeds
  ['peanuts', 'Dry-roasted peanuts', 'peanuts', 585, 24.4, 21.3, 49.7],
  ['almonds', 'Almonds', 'tree_nuts', 579, 21.2, 21.6, 49.9],
  ['almond_butter', 'Almond butter', 'tree_nuts', 614, 21, 18.8, 55.5],
  ['cashews', 'Cashews', 'tree_nuts', 553, 18.2, 30.2, 43.9],
  ['walnuts', 'Walnuts', 'tree_nuts', 654, 15.2, 13.7, 65.2],
  ['pistachios', 'Pistachios', 'tree_nuts', 562, 20.2, 27.2, 45.3],
  ['pecans', 'Pecans', 'tree_nuts', 691, 9.2, 13.9, 72],
  ['mixed_nuts', 'Mixed nuts', 'tree_nuts', 607, 20, 21, 54],
  ['flax', 'Ground flaxseed', 'seeds', 534, 18.3, 28.9, 42.2],
  ['hemp', 'Hemp hearts', 'seeds', 553, 31.6, 8.7, 48.8],
  ['pumpkin_seeds', 'Pumpkin seeds (pepitas)', 'seeds', 559, 30.2, 10.7, 49],
  ['sunflower_seeds', 'Sunflower seeds', 'seeds', 584, 20.8, 20, 51.5],
  ['sesame_seeds', 'Sesame seeds', 'seeds', 573, 17.7, 23.5, 49.7],
  // Oils & dressings
  ['avocado_oil', 'Avocado oil', 'oils', 884, 0, 0, 100],
  ['coconut_oil', 'Coconut oil', 'oils', 892, 0, 0, 99],
  ['canola_oil', 'Canola oil', 'oils', 884, 0, 0, 100],
  ['cooking_spray', 'Cooking spray', 'oils', 2, 0, 0, 0.2, { u: 'spray', g: 0.3, r: 'V' }],
  ['mayo', 'Mayonnaise', 'dressings', 680, 1, 0.6, 75],
  ['ranch', 'Ranch dressing', 'dressings', 430, 1.3, 6, 45],
  ['balsamic_vinaigrette', 'Balsamic vinaigrette', 'dressings', 300, 0.5, 12, 27],
  ['light_ranch', 'Light Greek-yogurt ranch', 'dressings', 150, 3, 8, 11],
  ['olives', 'Olives', 'olives', 115, 0.8, 6.3, 10.7],
  // Protein products
  ['whey_isolate', 'Whey protein isolate', 'whey', 370, 88, 3, 1.5],
  ['casein', 'Casein protein powder', 'other_protein', 360, 80, 8, 2],
  ['plant_protein', 'Plant protein powder (pea/rice)', 'other_protein', 380, 75, 8, 6],
  ['collagen', 'Collagen peptides', 'other_protein', 360, 90, 0, 0],
  ['protein_chips', 'Protein chips', 'bars', 140, 19, 5, 5, { u: 'bag', g: 32, a: 'Snacks' }],
  ['protein_bar_30', 'High-protein bar (~30 g protein)', 'bars', 290, 30, 25, 9, { u: 'bar', g: 68, a: 'Snacks' }],
  ['rtd_shake', 'Ready-to-drink protein shake (30 g)', 'rtd', 160, 30, 5, 3, { u: 'bottle', g: 325, a: 'Beverages' }],
  ['core_power', 'Ultra-filtered milk protein shake (26 g)', 'rtd', 170, 26, 8, 4.5, { u: 'bottle', g: 414, a: 'Beverages' }],
  // Sauces & pantry
  ['bbq_sauce', 'BBQ sauce', 'sauces', 172, 0.8, 40.8, 0.6],
  ['buffalo_sauce', 'Buffalo hot sauce', 'sauces', 11, 0.5, 1.8, 0.4],
  ['pesto', 'Basil pesto', 'sauces', 420, 5, 9, 42, { r: 'F' }],
  ['alfredo', 'Alfredo sauce', 'sauces', 150, 2.5, 4, 14, { r: 'F' }],
  ['tomato_paste', 'Tomato paste', 'sauces', 82, 4.3, 18.9, 0.5, { r: 'V' }],
  ['enchilada_sauce', 'Red enchilada sauce', 'sauces', 30, 1, 5, 1],
  ['hoisin', 'Hoisin sauce', 'sauces', 220, 3.3, 44, 3.4],
  ['tzatziki', 'Tzatziki', 'sauces', 95, 4, 4.5, 7, { a: 'Dairy & Eggs' }],
  ['mustard', 'Yellow mustard', 'condiments', 60, 3.7, 5.8, 3.3],
  ['dijon', 'Dijon mustard', 'condiments', 66, 4, 5.8, 3.4],
  ['hot_sauce', 'Hot sauce', 'condiments', 11, 0.5, 1.8, 0.4],
  ['relish', 'Sweet pickle relish', 'condiments', 130, 0.4, 35, 0.5, { r: 'V' }],
  ['sauerkraut', 'Sauerkraut', 'condiments', 19, 0.9, 4.3, 0.1],
  ['coconut_aminos', 'Coconut aminos', 'condiments', 60, 0, 13, 0],
  ['chicken_broth', 'Low-sodium chicken broth', 'spices', 6, 1, 0.3, 0.2, { ml: true }],
  ['beef_broth', 'Low-sodium beef broth', 'spices', 6, 1, 0.3, 0.2, { ml: true }],
  ['taco_seasoning', 'Taco / fajita seasoning', 'spices', 290, 5, 55, 5, { r: 'V' }],
  ['garlic_powder', 'Garlic powder', 'spices', 331, 16.6, 72.7, 0.7, { r: 'V' }],
  ['cinnamon', 'Cinnamon', 'spices', 247, 4, 81, 1.2, { r: 'V' }],
  // Sweets & snacks
  ['maple_syrup', 'Maple syrup', 'sweeteners', 260, 0, 67, 0.1],
  ['sugar', 'Sugar', 'sweeteners', 387, 0, 100, 0],
  ['brown_sugar', 'Brown sugar', 'sweeteners', 380, 0.1, 98, 0],
  ['agave', 'Agave syrup', 'sweeteners', 310, 0.1, 76, 0.5],
  ['jam', 'Fruit jam', 'sweeteners', 250, 0.4, 65, 0.1],
  ['zero_sweetener', 'Zero-calorie sweetener (stevia/monk fruit)', 'sweeteners', 0, 0, 0, 0, { r: 'V' }],
  ['dark_chocolate', 'Dark chocolate 70–85%', 'sweets', 598, 7.8, 45.9, 42.6],
  ['choc_chips', 'Semi-sweet chocolate chips', 'sweets', 479, 4.2, 63.9, 30],
  ['ice_cream', 'Vanilla ice cream', 'sweets', 207, 3.5, 23.6, 11, { a: 'Frozen' }],
  ['light_ice_cream', 'Light / protein ice cream', 'sweets', 95, 6.7, 19, 2.7, { a: 'Frozen' }],
  ['cookie', 'Chocolate chip cookie', 'sweets', 78, 0.9, 10.4, 3.8, { u: 'cookie', g: 16 }],
  ['gummies', 'Gummy candy', 'sweets', 343, 6.9, 77, 0],
  ['potato_chips', 'Potato chips', 'chips', 536, 7, 53, 34.6],
  ['tortilla_chips', 'Tortilla chips', 'chips', 489, 7, 64, 23],
  // Drinks
  ['orange_juice', 'Orange juice', 'juice', 45, 0.7, 10.4, 0.2, { ml: true }],
  ['apple_juice', 'Apple juice', 'juice', 46, 0.1, 11.3, 0.1, { ml: true }],
  ['sports_drink', 'Sports drink', 'juice', 24, 0, 6, 0, { ml: true }],
  ['coconut_water', 'Coconut water', 'juice', 19, 0.7, 3.7, 0.2, { ml: true }],
  ['coffee', 'Black coffee', 'zero_drinks', 1, 0.1, 0, 0, { ml: true }],
  ['tea', 'Unsweetened tea', 'zero_drinks', 1, 0, 0.3, 0, { ml: true }],
  ['diet_soda', 'Diet soda / sparkling water', 'zero_drinks', 0, 0, 0, 0, { ml: true }],
  ['cola', 'Regular cola', 'soda', 42, 0, 10.6, 0, { ml: true }],
  ['light_beer', 'Light beer', 'alcohol', 29, 0.2, 1.3, 0, { ml: true }],
  ['red_wine', 'Red wine', 'alcohol', 85, 0.1, 2.6, 0, { ml: true }],
  // ---- expanded list (v4) ----
  ['chicken_breast_skin', 'Chicken breast, with skin, raw', 'chicken_white', 172, 20.8, 0, 9.3],
  ['ground_chicken_breast', 'Ground chicken breast, raw', 'chicken_white', 110, 23, 0, 1.5],
  ['grilled_chicken_strips', 'Grilled chicken strips, precooked', 'chicken_white', 130, 24, 1, 3],
  ['chicken_leg_quarter', 'Chicken leg quarters, with skin, raw', 'chicken_dark', 214, 16.4, 0, 16],
  ['turkey_tenderloin', 'Turkey tenderloin, raw', 'turkey', 105, 24, 0, 1],
  ['roast_turkey', 'Roasted turkey breast, cooked', 'turkey', 147, 30, 0, 2.1],
  ['turkey_meatballs', 'Turkey meatballs, frozen, cooked', 'turkey', 190, 16, 6, 11, { a: 'Frozen' }],
  ['top_round', 'Top round / London broil, raw', 'beef_lean', 123, 23.5, 0, 3],
  ['tri_tip', 'Tri-tip, raw', 'beef_lean', 160, 21, 0, 8],
  ['beef_liver', 'Beef liver, raw', 'beef_lean', 135, 20.4, 3.9, 3.6],
  ['ground_beef_85', 'Ground beef 85/15, raw', 'beef_fatty', 215, 18.6, 0, 15],
  ['skirt_steak', 'Skirt steak, raw', 'beef_fatty', 197, 19.7, 0, 12.6],
  ['short_ribs', 'Beef short ribs, raw', 'beef_fatty', 388, 14.4, 0, 36],
  ['pork_chop_bone', 'Pork chop, bone-in, raw', 'pork', 172, 20.5, 0, 9.5],
  ['ham_steak', 'Ham steak', 'pork', 122, 19, 1.5, 4.5],
  ['pulled_pork', 'Pulled pork, cooked, unsauced', 'pork', 230, 24, 0, 14],
  ['pork_belly', 'Pork belly, raw', 'pork', 518, 9.3, 0, 53],
  ['lamb_chops', 'Lamb chops, raw', 'lamb', 282, 17, 0, 23],
  ['bison_steak', 'Bison steak, raw', 'lamb', 109, 21.6, 0, 1.8],
  ['elk', 'Elk, raw', 'lamb', 111, 23, 0, 1.5],
  ['duck_breast', 'Duck breast, skinless, raw', 'lamb', 123, 19.9, 0, 4.3],
  ['pastrami', 'Deli pastrami, lean', 'deli', 147, 21.8, 0.4, 5.8],
  ['prosciutto', 'Prosciutto', 'deli', 250, 26, 0.5, 16],
  ['bologna', 'Bologna', 'deli', 247, 11.5, 3, 20.5],
  ['chorizo', 'Chorizo, raw', 'sausage', 455, 24, 2, 38],
  ['bratwurst', 'Bratwurst, cooked', 'sausage', 297, 12, 3, 26],
  ['turkey_kielbasa', 'Turkey kielbasa', 'sausage', 150, 12, 5, 9],
  ['andouille', 'Andouille sausage', 'sausage', 280, 14, 2, 24],
  ['chicken_sausage_links', 'Chicken breakfast sausage links', 'sausage', 150, 14, 2, 9],
  ['chicken_jerky', 'Chicken jerky', 'jerky', 320, 46, 18, 5, { a: 'Snacks' }],
  ['biltong', 'Biltong', 'jerky', 265, 55, 2, 4, { a: 'Snacks' }],
  ['ahi_poke', 'Ahi poke, marinated', 'raw_fish', 140, 22, 4, 4],
  ['ikura', 'Salmon roe (ikura)', 'raw_fish', 250, 29, 3, 14],
  ['unagi', 'Unagi (sushi eel), glazed', 'raw_fish', 260, 22, 10, 15],
  ['tako', 'Octopus (tako), sushi-style', 'raw_fish', 164, 30, 4.4, 2.1],
  ['tuna_pouch', 'Tuna pouch, seasoned', 'canned_tuna', 105, 20, 2, 1.5, { a: 'Pantry' }],
  ['canned_mackerel', 'Canned mackerel, drained', 'canned_fish', 156, 23, 0, 6.3, { a: 'Pantry' }],
  ['anchovies', 'Anchovies in oil, drained', 'canned_fish', 210, 29, 0, 9.7, { a: 'Pantry' }],
  ['kippers', 'Kippered herring', 'canned_fish', 217, 24.6, 0, 12.4, { a: 'Pantry' }],
  ['arctic_char', 'Arctic char, raw', 'fatty_fish', 140, 20, 0, 6.5],
  ['black_cod', 'Sablefish (black cod), raw', 'fatty_fish', 195, 13.4, 0, 15.3],
  ['herring', 'Herring, raw', 'fatty_fish', 158, 18, 0, 9],
  ['pollock', 'Pollock, raw', 'white_fish', 92, 19.4, 0, 1],
  ['catfish', 'Catfish, raw', 'white_fish', 119, 15, 0, 6],
  ['flounder', 'Flounder / sole, raw', 'white_fish', 70, 12.4, 0, 1.9],
  ['haddock', 'Haddock, raw', 'white_fish', 74, 16.3, 0, 0.5],
  ['grouper', 'Grouper, raw', 'white_fish', 92, 19.4, 0, 1],
  ['breaded_fish', 'Breaded fish sticks / fillets, frozen', 'white_fish', 230, 12, 20, 11, { a: 'Frozen' }],
  ['cooked_shrimp', 'Shrimp, cooked, ready-to-eat', 'shellfish', 99, 24, 0.2, 0.3],
  ['clams', 'Clams, raw', 'shellfish', 86, 14.7, 3.6, 1],
  ['calamari', 'Calamari (squid), raw', 'shellfish', 92, 15.6, 3.1, 1.4],
  ['crawfish', 'Crawfish tails, cooked', 'shellfish', 82, 16.8, 0, 1.2],
  ['breaded_shrimp', 'Breaded / popcorn shrimp, frozen', 'shellfish', 240, 11, 22, 12, { a: 'Frozen' }],
  ['liquid_eggs', 'Liquid whole eggs', 'whole_eggs', 143, 12.6, 0.7, 9.5],
  ['egg_yolk', 'Egg yolk', 'whole_eggs', 55, 2.7, 0.6, 4.5, { u: 'yolk', g: 17 }],
  ['egg_bites', 'Egg bites (sous vide)', 'whole_eggs', 170, 12, 5, 11, { a: 'Frozen' }],
  ['duck_egg', 'Duck egg', 'whole_eggs', 130, 9, 1, 9.6, { u: 'egg', g: 70 }],
  ['goat_milk', 'Goat milk', 'milk', 69, 3.6, 4.5, 4.1, { ml: true }],
  ['lactose_free_milk', 'Lactose-free 2% milk', 'milk', 50, 3.3, 4.8, 2, { ml: true }],
  ['buttermilk', 'Low-fat buttermilk', 'milk', 40, 3.3, 4.8, 0.9, { ml: true }],
  ['pea_milk', 'Pea protein milk, unsweetened', 'milk_alt', 33, 3.3, 0, 1.9, { ml: true }],
  ['coconut_milk_bev', 'Coconut milk beverage, unsweetened', 'milk_alt', 20, 0.1, 0.6, 1.9, { ml: true }],
  ['cashew_milk', 'Cashew milk, unsweetened', 'milk_alt', 10, 0.4, 0.4, 0.8, { ml: true }],
  ['coconut_milk_can', 'Canned coconut milk, full-fat', 'milk_alt', 197, 2, 2.8, 21, { r: 'F', a: 'Pantry' }],
  ['coconut_milk_light', 'Canned coconut milk, light', 'milk_alt', 73, 0.7, 1.5, 7, { r: 'F', a: 'Pantry' }],
  ['protein_yogurt_cup', 'High-protein yogurt cup (Oikos Pro-style)', 'yogurt', 93, 13.3, 4.7, 2],
  ['nondairy_yogurt', 'Non-dairy yogurt (coconut/almond)', 'yogurt', 100, 1, 11, 6, { r: 'C' }],
  ['whole_yogurt', 'Plain whole-milk yogurt', 'yogurt', 61, 3.5, 4.7, 3.3],
  ['cottage_1', '1% cottage cheese', 'cottage', 72, 12.4, 2.7, 1],
  ['ricotta_whole', 'Whole-milk ricotta', 'cottage', 174, 11.3, 3, 13, { r: 'F' }],
  ['pepper_jack', 'Pepper jack cheese', 'cheese', 370, 23, 1, 30],
  ['monterey_jack', 'Monterey jack cheese', 'cheese', 373, 24.5, 0.7, 30],
  ['gouda', 'Gouda cheese', 'cheese', 356, 25, 2.2, 27.4],
  ['halloumi', 'Halloumi', 'cheese', 321, 21, 2, 25],
  ['babybel_light', 'Mini light cheese wheel (Babybel-style)', 'cheese', 50, 6, 0, 3, { u: 'piece', g: 20 }],
  ['fresh_mozz', 'Fresh mozzarella', 'soft_cheese', 254, 18, 3, 19],
  ['blue_cheese', 'Blue cheese', 'soft_cheese', 353, 21.4, 2.3, 28.7],
  ['whipped_cream', 'Whipped cream, aerosol', 'butter_cream', 257, 3.2, 12.5, 22],
  ['coffee_creamer', 'Flavored coffee creamer', 'butter_cream', 225, 0, 33, 10, { ml: true }],
  ['light_butter', 'Light butter spread', 'butter_cream', 360, 0, 0, 40],
  ['firm_tofu', 'Firm tofu', 'soy', 144, 17.3, 2.8, 8.7],
  ['baked_tofu', 'Baked tofu, marinated', 'soy', 160, 17, 5, 8],
  ['tvp', 'Textured soy protein (TVP), dry', 'soy', 330, 50, 30, 1, { a: 'Pantry' }],
  ['natto', 'Natto', 'soy', 211, 19.4, 12.7, 11],
  ['plant_nuggets', 'Plant-based chicken nuggets', 'seitan', 220, 13, 17, 11, { a: 'Frozen' }],
  ['veggie_burger', 'Black bean veggie burger', 'seitan', 180, 10, 18, 7, { a: 'Frozen' }],
  ['navy_beans', 'Navy beans, cooked', 'beans', 140, 8.2, 26, 0.6],
  ['lima_beans', 'Lima beans, cooked', 'beans', 115, 7.8, 20.9, 0.4],
  ['black_eyed_peas', 'Black-eyed peas, cooked', 'beans', 116, 7.7, 20.8, 0.5],
  ['red_lentils', 'Red lentils, cooked', 'lentils', 116, 9, 20, 0.4],
  ['roasted_chickpeas', 'Roasted chickpea snack', 'lentils', 400, 18, 55, 11, { a: 'Snacks' }],
  ['falafel', 'Falafel, baked', 'lentils', 333, 13.3, 31.8, 17.8, { a: 'Frozen' }],
  ['basmati_rice', 'Basmati rice, cooked', 'rice', 121, 3.5, 25, 0.4, { dry: 0.33, dryName: 'Basmati rice, dry' }],
  ['fried_rice', 'Fried rice', 'rice', 174, 4, 30, 4],
  ['spanish_rice', 'Spanish / Mexican rice', 'rice', 150, 3, 28, 3],
  ['sticky_rice', 'Sticky (glutinous) rice, cooked', 'rice', 97, 2, 21, 0.2],
  ['buckwheat', 'Buckwheat groats, cooked', 'ancient', 92, 3.4, 20, 0.6],
  ['millet', 'Millet, cooked', 'ancient', 119, 3.5, 23.7, 1],
  ['grits', 'Grits / polenta, cooked', 'ancient', 71, 1.7, 15.6, 0.5],
  ['amaranth', 'Amaranth, cooked', 'ancient', 102, 3.8, 18.7, 1.6],
  ['oat_bran', 'Oat bran, dry', 'oats', 375, 17.5, 57.5, 7.5],
  ['cream_of_wheat', 'Cream of wheat, dry', 'oats', 370, 10.6, 76, 1.4],
  ['muesli', 'Muesli', 'cereal', 360, 10, 66, 6],
  ['shredded_wheat', 'Shredded wheat', 'cereal', 360, 11, 80, 2],
  ['frosted_flakes', 'Frosted / sweetened flakes', 'cereal', 375, 4.5, 89, 0.5],
  ['puffed_rice', 'Crisp rice cereal', 'cereal', 390, 6, 87, 1],
  ['rye_bread', 'Rye bread', 'bread', 259, 8.5, 48.3, 3.3],
  ['brioche_bun', 'Brioche bun', 'bread', 330, 9, 50, 10],
  ['croissant', 'Croissant', 'bread', 406, 8.2, 45.8, 21],
  ['dinner_roll', 'Dinner roll', 'bread', 310, 10, 52, 6.5],
  ['hot_dog_bun', 'Hot dog bun', 'bread', 120, 4, 21.5, 2, { u: 'bun', g: 43 }],
  ['keto_bread', 'Low-carb / keto bread', 'bread', 45, 3, 9, 1, { u: 'slice', g: 28 }],
  ['lavash', 'Lavash / flatbread wrap', 'wraps', 290, 10, 55, 3],
  ['egg_white_wrap', 'Egg white wrap', 'wraps', 25, 5, 0.5, 0, { u: 'wrap', g: 28, a: 'Dairy & Eggs' }],
  ['rice_paper', 'Rice paper wrappers', 'wraps', 340, 6, 80, 0.5],
  ['pasta_cooked', 'Pasta, cooked', 'pasta', 158, 5.8, 30.9, 0.9],
  ['gnocchi', 'Potato gnocchi', 'pasta', 150, 4, 32, 0.5],
  ['instant_ramen', 'Instant ramen noodles, dry', 'pasta', 440, 10, 62, 17],
  ['udon', 'Udon noodles, cooked', 'pasta', 105, 2.6, 21.6, 0.4],
  ['lentil_pasta', 'Red lentil pasta, dry', 'pasta', 340, 25, 55, 2],
  ['tortellini', 'Cheese tortellini, refrigerated', 'pasta', 290, 12.5, 42, 8],
  ['palmini', 'Hearts of palm pasta (Palmini-style)', 'pasta', 20, 1, 4, 0, { r: 'V' }],
  ['mashed_potatoes', 'Mashed potatoes, prepared', 'potatoes', 113, 1.9, 17, 4.2],
  ['tater_tots', 'Tater tots, frozen', 'potatoes', 175, 2, 22, 9, { a: 'Frozen' }],
  ['potato_flakes', 'Instant mashed potato flakes, dry', 'potatoes', 354, 8.3, 81, 0.4, { a: 'Pantry' }],
  ['sweet_potato_fries', 'Sweet potato fries, frozen', 'potatoes', 180, 2, 26, 8, { a: 'Frozen' }],
  ['rice_crackers', 'Rice crackers', 'crackers', 390, 7, 82, 2, { a: 'Snacks' }],
  ['popcorn_light', 'Microwave popcorn, light', 'crackers', 430, 11, 73, 10, { a: 'Snacks' }],
  ['mini_rice_cakes', 'Mini rice cakes, flavored', 'crackers', 390, 6, 86, 2, { a: 'Snacks' }],
  ['wheat_flour', 'Whole-wheat flour', 'baking', 340, 13.2, 72, 2.5, { a: 'Pantry' }],
  ['oat_flour', 'Oat flour', 'baking', 404, 14.7, 65.7, 9.1, { a: 'Pantry' }],
  ['baking_mix', 'Baking mix (Bisquick-style)', 'baking', 430, 8, 68, 14, { a: 'Pantry' }],
  ['frozen_pancakes', 'Frozen pancakes', 'baking', 230, 6, 38, 6, { a: 'Frozen' }],
  ['cranberries', 'Cranberries, fresh', 'berries', 46, 0.5, 12, 0.1],
  ['acai', 'Açaí purée pack, unsweetened', 'berries', 70, 1, 4, 5, { a: 'Frozen' }],
  ['mandarins_can', 'Mandarin oranges, canned in juice', 'citrus', 37, 0.6, 9.6, 0, { a: 'Pantry' }],
  ['passion_fruit', 'Passion fruit', 'tropical', 97, 2.2, 23.4, 0.7],
  ['guava', 'Guava', 'tropical', 68, 2.6, 14.3, 1],
  ['dragon_fruit', 'Dragon fruit', 'tropical', 57, 0.4, 13, 0.4],
  ['lychee', 'Lychee', 'tropical', 66, 0.8, 16.5, 0.4],
  ['pomegranate', 'Pomegranate arils', 'tropical', 83, 1.7, 18.7, 1.2],
  ['plantain', 'Plantain', 'tropical', 122, 1.3, 32, 0.4],
  ['plum', 'Plum', 'tree_fruit', 46, 0.7, 11.4, 0.3],
  ['nectarine', 'Nectarine', 'tree_fruit', 44, 1.1, 10.6, 0.3],
  ['apricot', 'Apricot', 'tree_fruit', 48, 1.4, 11.1, 0.4],
  ['fig', 'Fig, fresh', 'tree_fruit', 74, 0.8, 19.2, 0.3],
  ['canned_peaches', 'Canned peaches in juice', 'tree_fruit', 44, 0.6, 11.6, 0, { a: 'Pantry' }],
  ['dried_apricots', 'Dried apricots', 'dried_fruit', 241, 3.4, 62.6, 0.5],
  ['dried_mango', 'Dried mango', 'dried_fruit', 319, 2.5, 78.6, 1.2],
  ['banana_chips', 'Banana chips', 'dried_fruit', 519, 2.3, 58, 33.6],
  ['fd_strawberries', 'Freeze-dried strawberries', 'dried_fruit', 370, 5, 85, 1],
  ['goji', 'Goji berries, dried', 'dried_fruit', 349, 14.3, 77, 0.4],
  ['swiss_chard', 'Swiss chard', 'leafy', 19, 1.8, 3.7, 0.2],
  ['collards', 'Collard greens', 'leafy', 32, 3, 5.4, 0.6],
  ['butter_lettuce', 'Butter lettuce', 'leafy', 13, 1.4, 2.2, 0.2],
  ['frozen_spinach', 'Spinach, frozen', 'leafy', 29, 3.6, 4.2, 0.6, { a: 'Frozen' }],
  ['fresh_herbs', 'Fresh herbs (cilantro, parsley, basil)', 'leafy', 23, 2.1, 3.7, 0.5],
  ['red_cabbage', 'Red cabbage', 'cruciferous', 31, 1.4, 7.4, 0.2],
  ['broccolini', 'Broccolini', 'cruciferous', 35, 3, 6, 0.5],
  ['shallots', 'Shallots', 'alliums', 72, 2.5, 16.8, 0.1],
  ['leeks', 'Leeks', 'alliums', 61, 1.5, 14.2, 0.3],
  ['roasted_peppers', 'Roasted red peppers, jarred', 'alliums', 28, 1, 5, 0.3, { a: 'Pantry' }],
  ['green_chiles', 'Diced green chiles, canned', 'alliums', 21, 0.7, 4.6, 0.1, { a: 'Pantry' }],
  ['turnips', 'Turnips', 'root_veg', 28, 0.9, 6.4, 0.1],
  ['jicama', 'Jicama', 'root_veg', 38, 0.7, 8.8, 0.1],
  ['ginger', 'Ginger root', 'root_veg', 80, 1.8, 17.8, 0.8],
  ['daikon', 'Daikon radish', 'root_veg', 18, 0.6, 4.1, 0.1],
  ['acorn_squash', 'Acorn squash', 'squash', 40, 0.8, 10.4, 0.1],
  ['zoodles', 'Zucchini noodles (zoodles)', 'squash', 17, 1.2, 3.1, 0.3],
  ['diced_tomatoes', 'Diced tomatoes, canned', 'tomatoes', 18, 0.8, 4, 0.1, { a: 'Pantry' }],
  ['sundried_tomatoes', 'Sun-dried tomatoes', 'tomatoes', 258, 14, 56, 3, { a: 'Pantry' }],
  ['tomatillos', 'Tomatillos', 'tomatoes', 32, 1, 5.8, 1],
  ['okra', 'Okra', 'other_veg', 33, 1.9, 7.5, 0.2],
  ['portobello', 'Portobello mushrooms', 'other_veg', 22, 2.1, 3.9, 0.4],
  ['hearts_of_palm', 'Hearts of palm, canned', 'other_veg', 28, 2.5, 4.6, 0.6, { a: 'Pantry' }],
  ['bean_sprouts', 'Bean sprouts', 'other_veg', 30, 3, 5.9, 0.2],
  ['water_chestnuts', 'Water chestnuts, canned', 'other_veg', 50, 0.9, 12.3, 0.1, { a: 'Pantry' }],
  ['snow_peas', 'Snow peas', 'other_veg', 42, 2.8, 7.6, 0.2],
  ['seaweed_salad', 'Seaweed salad', 'other_veg', 70, 1, 11, 3],
  ['honey_peanuts', 'Honey-roasted peanuts', 'peanuts', 580, 24, 28, 44, { a: 'Snacks' }],
  ['macadamia', 'Macadamia nuts', 'tree_nuts', 718, 7.9, 13.8, 75.8],
  ['hazelnuts', 'Hazelnuts', 'tree_nuts', 628, 15, 16.7, 60.8],
  ['brazil_nuts', 'Brazil nuts', 'tree_nuts', 659, 14.3, 11.7, 67],
  ['pine_nuts', 'Pine nuts', 'tree_nuts', 673, 13.7, 13.1, 68.4],
  ['cashew_butter', 'Cashew butter', 'tree_nuts', 587, 17.6, 27.6, 49.4],
  ['trail_mix', 'Trail mix', 'tree_nuts', 462, 13.8, 45, 29.4, { a: 'Snacks' }],
  ['sunbutter', 'Sunflower seed butter', 'seeds', 617, 17.3, 23.3, 55.2],
  ['tahini', 'Tahini', 'seeds', 595, 17, 21.2, 53.8],
  ['peanut_oil', 'Peanut oil', 'oils', 884, 0, 0, 100],
  ['grapeseed_oil', 'Grapeseed oil', 'oils', 884, 0, 0, 100],
  ['avocado_mayo', 'Avocado-oil mayo', 'dressings', 720, 0, 0, 80],
  ['caesar', 'Caesar dressing', 'dressings', 542, 2.2, 3.3, 57.8],
  ['italian_dressing', 'Italian dressing', 'dressings', 290, 0.4, 10, 27],
  ['honey_mustard', 'Honey mustard dressing', 'dressings', 460, 1, 23, 40],
  ['blue_cheese_dressing', 'Blue cheese dressing', 'dressings', 484, 1.4, 4.7, 51],
  ['thousand_island', 'Thousand Island dressing', 'dressings', 379, 1.1, 14.6, 35],
  ['kalamata', 'Kalamata olives', 'olives', 233, 1.3, 5, 23],
  ['green_olives', 'Green olives', 'olives', 145, 1, 3.8, 15.3],
  ['tapenade', 'Olive tapenade', 'olives', 280, 1, 5, 28],
  ['clear_whey', 'Clear whey isolate', 'whey', 352, 85, 3, 0],
  ['whey_casein', 'Whey-casein blend protein', 'other_protein', 380, 75, 12, 4],
  ['egg_white_powder', 'Egg white protein powder', 'other_protein', 360, 80, 5, 0],
  ['soy_isolate', 'Soy protein isolate', 'other_protein', 360, 85, 2, 3],
  ['granola_bar', 'Chewy granola bar', 'bars', 100, 1.5, 17, 3, { u: 'bar', g: 24, a: 'Snacks' }],
  ['protein_wafer', 'Protein wafer bar', 'bars', 190, 15, 17, 8, { u: 'bar', g: 40, a: 'Snacks' }],
  ['protein_water', 'Clear protein water (20 g)', 'rtd', 90, 20, 2, 0, { u: 'bottle', g: 500 }],
  ['plant_shake', 'Plant-based protein shake (20 g)', 'rtd', 160, 20, 9, 5, { u: 'bottle', g: 330 }],
  ['sweet_chili', 'Sweet chili sauce', 'sauces', 220, 0.5, 53, 0.5],
  ['pizza_sauce', 'Pizza sauce', 'sauces', 50, 1.5, 9, 1],
  ['curry_sauce', 'Curry / tikka masala simmer sauce', 'sauces', 110, 2, 9, 7],
  ['gochujang', 'Gochujang', 'sauces', 205, 4, 44, 1.5],
  ['peanut_sauce', 'Peanut (satay) sauce', 'sauces', 280, 8, 20, 19],
  ['chimichurri', 'Chimichurri', 'sauces', 398, 1, 4, 42],
  ['salsa_verde', 'Salsa verde', 'sauces', 30, 1, 6, 0.3],
  ['tomato_sauce', 'Tomato sauce, canned', 'sauces', 29, 1.2, 5.3, 0.3],
  ['worcestershire', 'Worcestershire sauce', 'condiments', 78, 0, 19.5, 0],
  ['fish_sauce', 'Fish sauce', 'condiments', 35, 5, 3.6, 0],
  ['horseradish', 'Horseradish', 'condiments', 48, 1.2, 11.3, 0.7],
  ['capers', 'Capers', 'condiments', 23, 2.4, 4.9, 0.9],
  ['pickled_jalapenos', 'Pickled jalapeños', 'condiments', 20, 0.9, 4, 0.4],
  ['pickled_onions', 'Pickled red onions', 'condiments', 40, 0.5, 9, 0],
  ['kimchi', 'Kimchi', 'condiments', 15, 1.1, 2.4, 0.5],
  ['cider_vinegar', 'Apple cider / rice vinegar', 'condiments', 21, 0, 0.9, 0, { ml: true }],
  ['balsamic', 'Balsamic vinegar', 'condiments', 88, 0.5, 17, 0, { ml: true }],
  ['salt', 'Salt', 'spices', 0, 0, 0, 0],
  ['black_pepper', 'Black pepper', 'spices', 251, 10, 64, 3.3],
  ['chili_powder', 'Chili powder', 'spices', 282, 13.5, 50, 14],
  ['paprika', 'Paprika', 'spices', 282, 14, 54, 13],
  ['cumin', 'Ground cumin', 'spices', 375, 17.8, 44, 22],
  ['italian_seasoning', 'Italian seasoning', 'spices', 265, 9, 64, 4],
  ['onion_powder', 'Onion powder', 'spices', 341, 10.4, 79, 1],
  ['vanilla', 'Vanilla extract', 'spices', 288, 0.1, 12.7, 0.1, { ml: true }],
  ['nutritional_yeast', 'Nutritional yeast', 'spices', 380, 50, 36, 4],
  ['bone_broth', 'Bone broth', 'spices', 19, 4.2, 0, 0.2, { ml: true }],
  ['veg_broth', 'Vegetable broth', 'spices', 5, 0.2, 1, 0, { ml: true }],
  ['chocolate_syrup', 'Chocolate syrup', 'sweeteners', 279, 2, 65, 1],
  ['powdered_sugar', 'Powdered sugar', 'sweeteners', 389, 0, 100, 0],
  ['coconut_sugar', 'Coconut sugar', 'sweeteners', 375, 1, 92, 0.5],
  ['molasses', 'Molasses', 'sweeteners', 290, 0, 74.7, 0.1],
  ['sf_pudding', 'Sugar-free pudding mix, dry', 'sweeteners', 330, 0, 83, 0],
  ['milk_chocolate', 'Milk chocolate', 'sweets', 535, 7.7, 59.4, 29.7],
  ['pb_cups', 'Peanut butter cups', 'sweets', 515, 10, 55, 30],
  ['brownie', 'Brownie', 'sweets', 466, 6, 50, 29],
  ['frozen_yogurt', 'Frozen yogurt', 'sweets', 159, 4, 24, 5.6, { a: 'Frozen' }],
  ['glazed_donut', 'Glazed donut', 'sweets', 421, 5.3, 50, 22.7],
  ['cheesecake', 'Cheesecake', 'sweets', 321, 5.5, 25.5, 22.5],
  ['blueberry_muffin', 'Blueberry muffin', 'sweets', 377, 4.4, 54, 16],
  ['rice_crispy_treat', 'Crispy rice treat', 'sweets', 90, 0.6, 17, 2.5, { u: 'bar', g: 22 }],
  ['pita_chips', 'Pita chips', 'chips', 457, 11, 64, 18],
  ['pork_rinds', 'Pork rinds', 'chips', 544, 61, 0, 31],
  ['cheese_crisps', 'Baked cheese crisps', 'chips', 540, 36, 4, 42],
  ['baked_chips', 'Baked potato chips', 'chips', 440, 6, 75, 12],
  ['veggie_straws', 'Veggie straws', 'chips', 520, 3, 63, 28],
  ['cheese_puffs', 'Cheese puffs', 'chips', 560, 6, 54, 36],
  ['cranberry_juice', 'Cranberry juice cocktail', 'juice', 54, 0, 13.5, 0, { ml: true }],
  ['grape_juice', 'Grape juice', 'juice', 60, 0.4, 14.8, 0.1, { ml: true }],
  ['lemonade', 'Lemonade', 'juice', 40, 0, 10, 0, { ml: true }],
  ['tart_cherry_juice', 'Tart cherry juice', 'juice', 55, 0.4, 13, 0.1, { ml: true }],
  ['kombucha', 'Kombucha', 'juice', 16, 0, 4, 0, { ml: true }],
  ['cold_brew', 'Cold brew coffee', 'zero_drinks', 2, 0.1, 0, 0, { ml: true }],
  ['sf_energy', 'Sugar-free energy drink', 'zero_drinks', 2, 0, 0.5, 0, { ml: true }],
  ['electrolyte_zero', 'Electrolyte drink, zero sugar', 'zero_drinks', 0, 0, 0, 0, { ml: true }],
  ['lemon_lime_soda', 'Lemon-lime soda', 'soda', 41, 0, 10.4, 0, { ml: true }],
  ['ginger_ale', 'Ginger ale', 'soda', 34, 0, 8.8, 0, { ml: true }],
  ['root_beer', 'Root beer', 'soda', 41, 0, 10.6, 0, { ml: true }],
  ['energy_drink', 'Energy drink (regular)', 'soda', 45, 0, 11, 0, { ml: true }],
  ['beer', 'Regular beer', 'alcohol', 43, 0.5, 3.6, 0, { ml: true }],
  ['white_wine', 'White wine', 'alcohol', 82, 0.1, 2.6, 0, { ml: true }],
  ['spirits', 'Spirits, 80-proof (vodka, whiskey…)', 'alcohol', 231, 0, 0, 0, { ml: true }],
  ['hard_seltzer', 'Hard seltzer', 'alcohol', 28, 0, 0.6, 0, { ml: true }],
  ['frozen_pizza', 'Frozen pizza, thin crust', 'frozen_meals', 270, 11, 30, 12],
  ['frozen_burrito', 'Frozen bean & cheese burrito', 'frozen_meals', 290, 10, 45, 8, { u: 'burrito', g: 142 }],
  ['protein_bowl_meal', 'High-protein frozen bowl meal', 'frozen_meals', 350, 30, 35, 10, { u: 'bowl', g: 283 }],
  ['chicken_nuggets', 'Chicken nuggets, frozen', 'frozen_meals', 260, 14, 16, 15],
  ['beef_meatballs', 'Beef meatballs, frozen', 'frozen_meals', 280, 13, 8, 22],
  ['chicken_tenders_breaded', 'Breaded chicken tenders, frozen', 'frozen_meals', 230, 15, 15, 12],
  ['potstickers', 'Pot stickers / dumplings, frozen', 'frozen_meals', 200, 8, 28, 6],
  ['frozen_lasagna', 'Lasagna, frozen', 'frozen_meals', 140, 8, 14, 6],
  ['burrito_bowl', 'Chicken burrito bowl (takeout)', 'takeout', 660, 45, 70, 22, { u: 'bowl', g: 500 }],
  ['cali_roll', 'California roll (8 pc)', 'takeout', 255, 9, 38, 7, { u: 'roll', g: 220 }],
  ['spicy_tuna_roll', 'Spicy tuna roll (8 pc)', 'takeout', 300, 14, 40, 10, { u: 'roll', g: 230 }],
  ['salmon_nigiri', 'Salmon nigiri (2 pc)', 'takeout', 110, 7, 14, 2.5, { u: 'order', g: 70 }],
  ['poke_bowl', 'Ahi poke bowl with rice (takeout)', 'takeout', 600, 38, 75, 16, { u: 'bowl', g: 450 }],
  ['cheeseburger', 'Cheeseburger, single (fast food)', 'takeout', 300, 15, 32, 13, { u: 'burger', g: 120 }],
  ['grilled_chicken_sandwich', 'Grilled chicken sandwich (fast food)', 'takeout', 390, 36, 44, 7, { u: 'sandwich', g: 200 }],
  ['pizza_slice', 'Pepperoni pizza slice, large', 'takeout', 300, 13, 34, 12, { u: 'slice', g: 110 }],
  ['grilled_chicken_salad', 'Grilled chicken salad (takeout)', 'takeout', 380, 36, 16, 20, { u: 'salad', g: 350 }],
  ['pad_thai', 'Chicken pad thai (takeout)', 'takeout', 730, 32, 90, 26, { u: 'plate', g: 400 }],
  ['chicken_noodle_soup', 'Chicken noodle soup, canned', 'soups', 31, 2, 3.8, 0.9],
  ['chili_beans', 'Chili with beans, canned', 'soups', 110, 7.5, 12, 3.5],
  ['lentil_soup', 'Lentil soup', 'soups', 59, 3.5, 9, 1],
  ['tomato_soup', 'Tomato soup', 'soups', 41, 1, 7, 1],
  ['minestrone', 'Minestrone', 'soups', 37, 1.5, 6, 0.8],
  ['clam_chowder', 'Clam chowder', 'soups', 80, 3, 8, 4],
  ['miso_soup', 'Miso soup', 'soups', 16, 1.2, 1.8, 0.5, { ml: true }]
];
MORE_FOODS.forEach(([id, n, sub, k, p, c, f, o = {}]) => {
  if (BASE_ING[id]) return;
  const g = { n, a: o.a || SUB_AISLE[sub] || CAT_AISLE[SUB_CAT[sub]] || 'Pantry', r: o.r || defaultRole(sub, k, p, c, f), k, p, c, f };
  if (o.u) { g.u = o.u; g.g = o.g; }
  if (o.ml) g.ml = true;
  if (o.dry) { g.dry = o.dry; g.dryName = o.dryName; }
  BASE_ING[id] = g; BASE_SUB[id] = sub;
});

/* ---------- food emoji list for the recipe editor (Unicode "Food & Drink", Emoji ≤ 15.0) ---------- */
const FOOD_EMOJI = [
  ['Fruit', [['🍇', 'grapes'], ['🍈', 'melon'], ['🍉', 'watermelon'], ['🍊', 'orange tangerine'], ['🍋', 'lemon'], ['🍌', 'banana'], ['🍍', 'pineapple'], ['🥭', 'mango'], ['🍎', 'red apple'], ['🍏', 'green apple'], ['🍐', 'pear'], ['🍑', 'peach'], ['🍒', 'cherries'], ['🍓', 'strawberry'], ['🫐', 'blueberries'], ['🥝', 'kiwi'], ['🍅', 'tomato'], ['🫒', 'olive'], ['🥥', 'coconut']]],
  ['Vegetables', [['🥑', 'avocado'], ['🍆', 'eggplant'], ['🥔', 'potato'], ['🥕', 'carrot'], ['🌽', 'corn'], ['🌶️', 'hot pepper chili'], ['🫑', 'bell pepper'], ['🥒', 'cucumber pickle'], ['🥬', 'leafy greens lettuce'], ['🥦', 'broccoli'], ['🧄', 'garlic'], ['🧅', 'onion'], ['🍄', 'mushroom'], ['🥜', 'peanuts'], ['🫘', 'beans'], ['🌰', 'chestnut'], ['🫚', 'ginger root'], ['🫛', 'pea pod edamame']]],
  ['Prepared food', [['🍞', 'bread'], ['🥐', 'croissant'], ['🥖', 'baguette'], ['🫓', 'flatbread pita naan'], ['🥨', 'pretzel'], ['🥯', 'bagel'], ['🥞', 'pancakes'], ['🧇', 'waffle'], ['🧀', 'cheese'], ['🍖', 'meat on bone'], ['🍗', 'poultry leg chicken'], ['🥩', 'steak meat'], ['🥓', 'bacon'], ['🍔', 'hamburger burger'], ['🍟', 'fries'], ['🍕', 'pizza'], ['🌭', 'hot dog'], ['🥪', 'sandwich'], ['🌮', 'taco'], ['🌯', 'burrito wrap'], ['🫔', 'tamale'], ['🥙', 'stuffed flatbread gyro'], ['🧆', 'falafel'], ['🥚', 'egg'], ['🍳', 'fried egg cooking'], ['🥘', 'paella pan'], ['🍲', 'pot of food stew chili soup'], ['🫕', 'fondue'], ['🥣', 'bowl with spoon oats cereal'], ['🥗', 'green salad'], ['🍿', 'popcorn'], ['🧈', 'butter'], ['🧂', 'salt'], ['🥫', 'canned food']]],
  ['Asian food', [['🍱', 'bento box'], ['🍘', 'rice cracker'], ['🍙', 'rice ball onigiri'], ['🍚', 'cooked rice'], ['🍛', 'curry rice'], ['🍜', 'ramen noodles'], ['🍝', 'spaghetti pasta'], ['🍠', 'roasted sweet potato'], ['🍢', 'oden skewer'], ['🍣', 'sushi'], ['🍤', 'fried shrimp tempura'], ['🍥', 'fish cake'], ['🥮', 'moon cake'], ['🍡', 'dango'], ['🥟', 'dumpling'], ['🥠', 'fortune cookie'], ['🥡', 'takeout box']]],
  ['Seafood', [['🦀', 'crab'], ['🦞', 'lobster'], ['🦐', 'shrimp'], ['🦑', 'squid'], ['🦪', 'oyster'], ['🐟', 'fish'], ['🐠', 'tropical fish'], ['🐙', 'octopus']]],
  ['Sweets', [['🍦', 'soft ice cream'], ['🍧', 'shaved ice'], ['🍨', 'ice cream'], ['🍩', 'doughnut'], ['🍪', 'cookie'], ['🎂', 'birthday cake'], ['🍰', 'shortcake'], ['🧁', 'cupcake muffin'], ['🥧', 'pie'], ['🍫', 'chocolate bar'], ['🍬', 'candy'], ['🍭', 'lollipop'], ['🍮', 'custard pudding'], ['🍯', 'honey pot']]],
  ['Drinks', [['🍼', 'baby bottle milk'], ['🥛', 'glass of milk'], ['☕', 'coffee'], ['🫖', 'teapot'], ['🍵', 'tea'], ['🍶', 'sake'], ['🍾', 'champagne'], ['🍷', 'wine'], ['🍸', 'cocktail'], ['🍹', 'tropical drink smoothie'], ['🍺', 'beer'], ['🍻', 'beers'], ['🥂', 'clinking glasses'], ['🥃', 'tumbler whiskey'], ['🫗', 'pouring liquid'], ['🥤', 'cup with straw shake'], ['🧋', 'bubble tea'], ['🧃', 'juice box'], ['🧉', 'mate'], ['🧊', 'ice']]],
  ['Dishware', [['🥢', 'chopsticks'], ['🍽️', 'plate fork knife'], ['🍴', 'fork and knife'], ['🥄', 'spoon'], ['🔪', 'kitchen knife'], ['🫙', 'jar meal prep']]]
];

/* ---------- shopping model: typical package size + how fast a food spoils ----------
   Package size is in the food's own basis: grams, ml (for per-100 ml foods) or items (for per-item foods).
   Spoil weight w: 1 = fresh, use within about a week (raw meat, leafy greens) … 0 = pantry staple that keeps for months. */
const SUB_PACK = {
  chicken_white: 680, chicken_dark: 680, turkey: 454, beef_lean: 454, beef_fatty: 454, pork: 570, lamb: 454, deli: 255, sausage: 340, jerky: 85,
  raw_fish: 227, canned_tuna: 113, canned_fish: 120, fatty_fish: 454, white_fish: 454, shellfish: 454,
  whole_eggs: 12, egg_whites: 454, milk: 1540, milk_alt: 1890, yogurt: 907, cottage: 680, cheese: 227, soft_cheese: 170, butter_cream: 454,
  soy: 397, seitan: 227, beans: 250, lentils: 425,
  rice: 2500, ancient: 1000, oats: 1190, cereal: 400, bread: 20, wraps: 8, pasta: 454, potatoes: 2270, crackers: 200, baking: 680,
  berries: 340, citrus: 4, tropical: 454, tree_fruit: 6, melon: 1000, dried_fruit: 170, avocado: 170,
  leafy: 142, cruciferous: 340, alliums: 450, root_veg: 454, squash: 454, tomatoes: 283, other_veg: 340,
  peanuts: 454, tree_nuts: 454, seeds: 340, oils: 500, dressings: 425, olives: 170,
  whey: 907, other_protein: 907, bars: 12, rtd: 4, sauces: 425, condiments: 400, spices: 100,
  frozen_meals: 1, takeout: 1, soups: 540, sweeteners: 340, sweets: 200, chips: 227, juice: 1890, zero_drinks: 2000, soda: 2000, alcohol: 2130
};
const SUB_W = {
  chicken_white: 1, chicken_dark: 1, turkey: 1, beef_lean: 1, beef_fatty: 1, pork: 1, lamb: 1, deli: .9, sausage: .6, jerky: .1,
  raw_fish: 1, canned_tuna: .05, canned_fish: .05, fatty_fish: 1, white_fish: 1, shellfish: .5,
  whole_eggs: .5, egg_whites: .8, milk: .8, milk_alt: .5, yogurt: .7, cottage: .8, cheese: .3, soft_cheese: .6, butter_cream: .4,
  soy: .7, seitan: .6, beans: .05, lentils: .05, rice: .05, ancient: .05, oats: .05, cereal: .1, bread: .6, wraps: .4, pasta: .03, potatoes: .3, crackers: .1, baking: .05,
  berries: 1, citrus: .4, tropical: .8, tree_fruit: .4, melon: .9, dried_fruit: .05, avocado: 1,
  leafy: 1, cruciferous: .9, alliums: .6, root_veg: .3, squash: .5, tomatoes: .8, other_veg: .7,
  peanuts: .03, tree_nuts: .05, seeds: .03, oils: 0, dressings: .1, olives: .1, whey: .02, other_protein: .02, bars: 0, rtd: .05,
  sauces: .3, condiments: .03, spices: 0, frozen_meals: .1, takeout: 1, soups: .05, sweeteners: 0, sweets: .2, chips: .1, juice: .4, zero_drinks: .05, soda: .05, alcohol: .05
};
// Specific foods that differ from their subgroup
const FOOD_PACK = {
  spinach: 142, romaine: 283, bell_pepper: 450, onion: 1360, red_onion: 1360, garlic: 60, potato: 2270, sweet_potato: 900, cucumber: 300, cherry_tomato: 283, celery: 454, carrots: 454,
  broccoli: 340, asparagus: 454, green_beans: 340, avocado: 170, pineapple: 454, banana: 6, berries: 454, corn: 340, stir_fry_veg: 454, edamame: 340, tofu: 397,
  greek_yogurt: 907, cottage: 680, cheese_shred: 227, feta: 170, parmesan: 142, string_cheese: 12, egg_whites: 454, fairlife: 1540,
  chicken_breast: 680, chicken_thigh: 680, turkey_937: 454, beef_937: 454, sirloin: 454, pork_tenderloin: 570, canadian_bacon: 170, deli_turkey: 255,
  ahi: 227, salmon: 227, salmon_fillet: 454, shrimp: 454, tuna_can: 113, rice: 2500, sushi_rice: 2500, quinoa: 1000, oats: 1190, granola: 340, kodiak: 680, protein_pasta: 340,
  black_beans: 250, kidney_beans: 250, crushed_tomatoes: 794, marinara: 680, salsa: 454, teriyaki: 290, honey: 340, pb: 454, pb2: 184, whey: 907, chia: 340,
  olive_oil: 500, sesame_oil: 150, light_mayo: 850, soy_sauce: 296, sriracha: 482, ketchup: 567, pickles: 680, nori: 10, cornstarch: 454, cocoa: 227, jerky: 85,
  protein_bar: 12, rice_cake: 14, apple: 6, bread: 20, english_muffin: 6, tortilla_lg: 8, tortilla_sm: 10, syrup_sf: 355, egg: 12, egg_boiled: 6, egg_jumbo: 12, duck_egg: 6,
  bacon: 16, hot_dog: 8, meat_stick: 10, american_cheese: 16, babybel_light: 6, instant_oats: 10, white_bread: 20, sourdough: 16, ezekiel: 20, bagel: 6, bagel_thin: 8,
  burger_bun: 8, hot_dog_bun: 8, ww_pita: 6, naan: 4, flour_tortilla: 10, corn_tortilla: 30, lowcarb_tortilla: 8, egg_white_wrap: 6, keto_bread: 18, frozen_waffle: 10,
  orange: 4, clementine: 12, grapefruit: 2, kiwi: 6, pear: 4, peach: 4, dates: 20, cooking_spray: 400, protein_chips: 8, protein_bar_30: 12, rtd_shake: 4, core_power: 4,
  cookie: 12, egg_yolk: 12, granola_bar: 8, protein_wafer: 12, protein_water: 12, plant_shake: 4, rice_crispy_treat: 8
};
const FOOD_W = { onion: .2, red_onion: .2, garlic: .1, potato: .2, sweet_potato: .3, carrots: .4, apple: .3, egg: .4, parmesan: .15, string_cheese: .3, pickles: .1, ketchup: 0, soy_sauce: 0, sriracha: 0, honey: 0, pb: .02 };
