// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Oroshi-zz
/* ============================================================
   FORGE 90 — Ingredients (USDA-based) and recipes
   Macros per 100 g, or per unit when `u` is set.
   Role drives portion scaling:
     P = protein source (scaled to hit protein target)
     C = carb source, F = fat source (scaled to hit calorie target)
     V = vegetables / sauces / seasonings (held constant)
   ============================================================ */
const BASE_ING = {
  // Meat & seafood
  chicken_breast: { n: 'Chicken breast, raw', a: 'Meat & Seafood', r: 'P', k: 120, p: 22.5, c: 0, f: 2.6 },
  chicken_thigh:  { n: 'Chicken thighs, boneless skinless, raw', a: 'Meat & Seafood', r: 'P', k: 121, p: 19.7, c: 0, f: 4.1 },
  turkey_937:     { n: 'Ground turkey 93/7, raw', a: 'Meat & Seafood', r: 'P', k: 150, p: 18.7, c: 0, f: 8.3 },
  beef_937:       { n: 'Ground beef 93/7, raw', a: 'Meat & Seafood', r: 'P', k: 152, p: 20.9, c: 0, f: 7 },
  sirloin:        { n: 'Top sirloin / flank steak, raw', a: 'Meat & Seafood', r: 'P', k: 140, p: 22, c: 0, f: 5.5 },
  pork_tenderloin:{ n: 'Pork tenderloin, raw', a: 'Meat & Seafood', r: 'P', k: 109, p: 21, c: 0, f: 2.2 },
  canadian_bacon: { n: 'Canadian bacon', a: 'Meat & Seafood', r: 'P', k: 107, p: 17.9, c: 1.8, f: 2.7 },
  deli_turkey:    { n: 'Deli turkey breast', a: 'Meat & Seafood', r: 'P', k: 95, p: 18, c: 2.5, f: 1.5 },
  ahi:            { n: 'Sushi-grade ahi tuna', a: 'Meat & Seafood', r: 'P', k: 109, p: 24.4, c: 0, f: 0.5 },
  salmon:         { n: 'Sushi-grade salmon', a: 'Meat & Seafood', r: 'P', k: 208, p: 20.4, c: 0, f: 13.4 },
  tuna_can:       { n: 'Canned light tuna in water, drained', a: 'Pantry', r: 'P', k: 116, p: 25.5, c: 0, f: 0.8 },
  jerky:          { n: 'Beef jerky', a: 'Snacks', r: 'P', k: 286, p: 43, c: 21, f: 3.6 },
  // Dairy & eggs
  egg:            { n: 'Large eggs', a: 'Dairy & Eggs', r: 'P', u: 'egg', g: 50, k: 72, p: 6.3, c: 0.4, f: 4.8 },
  egg_whites:     { n: 'Liquid egg whites', a: 'Dairy & Eggs', r: 'P', k: 52, p: 10.9, c: 0.7, f: 0.2, ml: true },
  greek_yogurt:   { n: 'Nonfat plain Greek yogurt', a: 'Dairy & Eggs', r: 'P', k: 59, p: 10.3, c: 3.6, f: 0.4 },
  cottage:        { n: '2% cottage cheese', a: 'Dairy & Eggs', r: 'P', k: 82, p: 10.5, c: 4.8, f: 2.3 },
  fairlife:       { n: 'Ultra-filtered fat-free milk (Fairlife)', a: 'Dairy & Eggs', r: 'P', k: 33, p: 5.4, c: 2.5, f: 0, ml: true },
  cheese_shred:   { n: 'Reduced-fat shredded cheese', a: 'Dairy & Eggs', r: 'F', k: 286, p: 25, c: 3.6, f: 21.4 },
  feta:           { n: 'Feta cheese', a: 'Dairy & Eggs', r: 'F', k: 264, p: 14.2, c: 4.1, f: 21.3 },
  parmesan:       { n: 'Parmesan, grated', a: 'Dairy & Eggs', r: 'F', k: 420, p: 29.6, c: 13.9, f: 27.8 },
  string_cheese:  { n: 'String cheese (part-skim)', a: 'Dairy & Eggs', r: 'F', u: 'stick', g: 28, k: 80, p: 7, c: 1, f: 5.5 },
  // Pantry / protein
  whey:           { n: 'Whey protein powder', a: 'Pantry', r: 'P', k: 400, p: 80, c: 10, f: 5 },
  pb2:            { n: 'Powdered peanut butter (PB2)', a: 'Pantry', r: 'P', k: 462, p: 46, c: 38, f: 11.5 },
  protein_bar:    { n: 'Protein bar (~20 g protein)', a: 'Snacks', r: 'P', u: 'bar', g: 60, k: 200, p: 20, c: 21, f: 7 },
  // Grains & starches
  oats:           { n: 'Rolled oats', a: 'Grains & Bread', r: 'C', k: 379, p: 13.2, c: 67.7, f: 6.5 },
  rice:           { n: 'White/jasmine rice, cooked', a: 'Grains & Bread', r: 'C', k: 130, p: 2.7, c: 28.2, f: 0.3, dry: 0.33, dryName: 'White/jasmine rice, uncooked' },
  sushi_rice:     { n: 'Sushi rice, seasoned, cooked', a: 'Grains & Bread', r: 'C', k: 150, p: 2.6, c: 33, f: 0.3, dry: 0.4, dryName: 'Sushi rice, uncooked' },
  quinoa:         { n: 'Quinoa, cooked', a: 'Grains & Bread', r: 'C', k: 120, p: 4.4, c: 21.3, f: 1.9, dry: 0.37, dryName: 'Quinoa, uncooked' },
  protein_pasta:  { n: 'Protein pasta, dry', a: 'Grains & Bread', r: 'C', k: 339, p: 17.9, c: 67.9, f: 2.7 },
  kodiak:         { n: 'Protein pancake mix (Kodiak-style)', a: 'Grains & Bread', r: 'C', k: 358, p: 26.4, c: 56.6, f: 3.8 },
  tortilla_lg:    { n: 'Whole-wheat tortilla, 10-in', a: 'Grains & Bread', r: 'C', u: 'tortilla', g: 70, k: 210, p: 6, c: 35, f: 5 },
  tortilla_sm:    { n: 'Whole-wheat tortilla, 8-in', a: 'Grains & Bread', r: 'C', u: 'tortilla', g: 45, k: 130, p: 4, c: 22, f: 3.5 },
  bread:          { n: 'Whole-wheat bread', a: 'Grains & Bread', r: 'C', u: 'slice', g: 32, k: 80, p: 4, c: 14, f: 1 },
  english_muffin: { n: 'Whole-wheat English muffin', a: 'Grains & Bread', r: 'C', u: 'muffin', g: 66, k: 130, p: 5, c: 26, f: 1.5 },
  rice_cake:      { n: 'Rice cakes', a: 'Grains & Bread', r: 'C', u: 'cake', g: 9, k: 35, p: 0.7, c: 7.3, f: 0.3 },
  granola:        { n: 'Low-sugar granola', a: 'Grains & Bread', r: 'C', k: 450, p: 10, c: 64, f: 18 },
  sweet_potato:   { n: 'Sweet potato', a: 'Produce', r: 'C', k: 86, p: 1.6, c: 20.1, f: 0.1 },
  potato:         { n: 'Russet / baby potatoes', a: 'Produce', r: 'C', k: 79, p: 2.1, c: 18.1, f: 0.1 },
  black_beans:    { n: 'Black beans, canned, drained', a: 'Pantry', r: 'C', k: 132, p: 8.9, c: 23.7, f: 0.5 },
  kidney_beans:   { n: 'Kidney beans, canned, drained', a: 'Pantry', r: 'C', k: 127, p: 8.7, c: 22.8, f: 0.5 },
  corn:           { n: 'Sweet corn, frozen', a: 'Frozen', r: 'C', k: 86, p: 3.3, c: 18.7, f: 1.4 },
  edamame:        { n: 'Shelled edamame, frozen', a: 'Frozen', r: 'P', k: 121, p: 11.9, c: 8.9, f: 5.2 },
  // Fruit
  banana:         { n: 'Banana, medium', a: 'Produce', r: 'C', u: 'banana', g: 118, k: 105, p: 1.3, c: 27, f: 0.4 },
  apple:          { n: 'Apple, medium', a: 'Produce', r: 'C', u: 'apple', g: 182, k: 95, p: 0.5, c: 25, f: 0.3 },
  berries:        { n: 'Mixed berries (fresh or frozen)', a: 'Frozen', r: 'C', k: 50, p: 0.7, c: 12, f: 0.3 },
  pineapple:      { n: 'Pineapple chunks', a: 'Produce', r: 'C', k: 50, p: 0.5, c: 13, f: 0.1 },
  // Sweeteners & sauces
  honey:          { n: 'Honey', a: 'Pantry', r: 'C', k: 304, p: 0.3, c: 82.4, f: 0 },
  syrup_sf:       { n: 'Sugar-free syrup', a: 'Pantry', r: 'V', k: 33, p: 0, c: 8, f: 0, ml: true },
  teriyaki:       { n: 'Teriyaki sauce', a: 'Pantry', r: 'C', k: 89, p: 5.9, c: 15.6, f: 0 },
  marinara:       { n: 'Marinara sauce', a: 'Pantry', r: 'C', k: 50, p: 1.5, c: 8, f: 1.5 },
  crushed_tomatoes:{ n: 'Crushed tomatoes, canned', a: 'Pantry', r: 'V', k: 32, p: 1.6, c: 7.3, f: 0.3 },
  salsa:          { n: 'Salsa', a: 'Pantry', r: 'V', k: 36, p: 1.5, c: 7, f: 0.2 },
  ketchup:        { n: 'Ketchup', a: 'Pantry', r: 'V', k: 101, p: 1, c: 27, f: 0.1 },
  cornstarch:     { n: 'Cornstarch', a: 'Pantry', r: 'V', k: 381, p: 0.3, c: 91, f: 0.1 },
  soy_sauce:      { n: 'Low-sodium soy sauce', a: 'Pantry', r: 'V', k: 53, p: 8.1, c: 4.9, f: 0.6, ml: true },
  sriracha:       { n: 'Sriracha', a: 'Pantry', r: 'V', k: 93, p: 1.9, c: 19, f: 0.9 },
  cocoa:          { n: 'Unsweetened cocoa powder', a: 'Pantry', r: 'V', k: 228, p: 19.6, c: 57.9, f: 13.7 },
  // Fats
  olive_oil:      { n: 'Olive oil', a: 'Pantry', r: 'F', k: 884, p: 0, c: 0, f: 100 },
  sesame_oil:     { n: 'Toasted sesame oil', a: 'Pantry', r: 'F', k: 884, p: 0, c: 0, f: 100 },
  pb:             { n: 'Peanut butter', a: 'Pantry', r: 'F', k: 588, p: 25, c: 20, f: 50 },
  chia:           { n: 'Chia seeds', a: 'Pantry', r: 'F', k: 486, p: 16.5, c: 42, f: 30.7 },
  avocado:        { n: 'Avocado', a: 'Produce', r: 'F', k: 160, p: 2, c: 8.5, f: 14.7 },
  light_mayo:     { n: 'Light mayonnaise', a: 'Pantry', r: 'F', k: 233, p: 0, c: 6.7, f: 23 },
  // Vegetables
  spinach:        { n: 'Baby spinach', a: 'Produce', r: 'V', k: 23, p: 2.9, c: 3.6, f: 0.4 },
  bell_pepper:    { n: 'Bell peppers', a: 'Produce', r: 'V', k: 28, p: 1, c: 6, f: 0.3 },
  onion:          { n: 'Onion', a: 'Produce', r: 'V', k: 40, p: 1.1, c: 9.3, f: 0.1 },
  broccoli:       { n: 'Broccoli florets', a: 'Produce', r: 'V', k: 34, p: 2.8, c: 6.6, f: 0.4 },
  stir_fry_veg:   { n: 'Stir-fry vegetable blend, frozen', a: 'Frozen', r: 'V', k: 35, p: 2, c: 7, f: 0.2 },
  green_beans:    { n: 'Green beans', a: 'Produce', r: 'V', k: 31, p: 1.8, c: 7, f: 0.2 },
  asparagus:      { n: 'Asparagus', a: 'Produce', r: 'V', k: 20, p: 2.2, c: 3.9, f: 0.1 },
  romaine:        { n: 'Romaine lettuce', a: 'Produce', r: 'V', k: 17, p: 1.2, c: 3.3, f: 0.3 },
  cucumber:       { n: 'Cucumber', a: 'Produce', r: 'V', k: 15, p: 0.7, c: 3.6, f: 0.1 },
  cherry_tomato:  { n: 'Cherry tomatoes', a: 'Produce', r: 'V', k: 18, p: 0.9, c: 3.9, f: 0.2 },
  celery:         { n: 'Celery', a: 'Produce', r: 'V', k: 14, p: 0.7, c: 3, f: 0.2 },
  carrots:        { n: 'Baby carrots', a: 'Produce', r: 'V', k: 41, p: 0.9, c: 9.6, f: 0.2 },
  pickles:        { n: 'Dill pickles', a: 'Pantry', r: 'V', k: 12, p: 0.5, c: 2.4, f: 0.3 },
  nori:           { n: 'Nori sheets', a: 'Pantry', r: 'V', u: 'sheet', g: 3, k: 8, p: 1.2, c: 1.2, f: 0.1 },
  // extra options (off/on via Food preferences)
  salmon_fillet:  { n: 'Salmon fillet, raw (to cook)', a: 'Meat & Seafood', r: 'P', k: 208, p: 20.4, c: 0, f: 13.4 },
  shrimp:         { n: 'Shrimp, peeled, raw', a: 'Meat & Seafood', r: 'P', k: 85, p: 20.1, c: 0, f: 0.5 },
  tofu:           { n: 'Extra-firm tofu', a: 'Produce', r: 'P', k: 144, p: 17.3, c: 2.8, f: 8.7 }
};

/* Recipes: ingredient amounts are for the WHOLE recipe (all servings).
   yield = servings produced. storage: fridge (eat within 4 days), freezer (freezes well), fresh (eat same day). */
const BASE_RECIPES = [
  /* ---------------- BREAKFAST ---------------- */
  { id: 'overnight_oats', name: 'Protein Overnight Oats', cat: 'breakfast', emoji: '🥣', yield: 1, storage: 'fridge', time: 5,
    tags: ['No-cook', 'Make the night before'],
    ing: [['oats', 50], ['whey', 30], ['greek_yogurt', 150], ['fairlife', 150], ['berries', 80], ['chia', 8]],
    steps: ['Stir oats, whey, chia, yogurt and milk together in a jar until smooth.', 'Top with berries, seal, and refrigerate overnight (or at least 4 h).', 'Eat cold or microwave 60–90 s. Tip: make 2–3 jars at once — they keep 3 days.'] },
  { id: 'egg_white_omelette', name: 'Veggie Egg-White Omelette & Toast', cat: 'breakfast', emoji: '🍳', yield: 1, storage: 'fresh', time: 12,
    tags: ['Quick', 'Classic'],
    ing: [['egg', 2], ['egg_whites', 200], ['spinach', 40], ['bell_pepper', 60], ['onion', 30], ['cheese_shred', 20], ['bread', 1], ['salsa', 30]],
    steps: ['Sauté diced pepper and onion in a nonstick pan with cooking spray for 3 min; add spinach until wilted.', 'Whisk eggs and egg whites, pour over the vegetables, and cook on medium-low.', 'When nearly set, add cheese, fold, and cook 30 s more.', 'Serve with toast and salsa.'] },
  { id: 'protein_pancakes', name: 'Protein Pancakes', cat: 'breakfast', emoji: '🥞', yield: 1, storage: 'fresh', time: 15,
    tags: ['Weekend favorite'],
    ing: [['kodiak', 70], ['egg_whites', 100], ['fairlife', 100], ['berries', 80], ['greek_yogurt', 100], ['syrup_sf', 30]],
    steps: ['Whisk pancake mix, egg whites and milk into a thick batter (rest 2 min).', 'Cook ¼-cup pancakes on a greased griddle over medium heat, flipping when bubbles form.', 'Top with Greek yogurt, berries and sugar-free syrup.'] },
  { id: 'breakfast_burritos', name: 'Freezer Breakfast Burritos', cat: 'breakfast', emoji: '🌯', yield: 4, storage: 'freezer', time: 30,
    tags: ['Meal prep', 'Freezes 2 months'],
    ing: [['egg', 4], ['egg_whites', 400], ['turkey_937', 340], ['potato', 200], ['bell_pepper', 150], ['onion', 100], ['cheese_shred', 40], ['tortilla_lg', 4], ['salsa', 120]],
    steps: ['Dice the potato small and cook in a covered skillet with a splash of water until tender, then brown.', 'Brown the turkey with sage, garlic powder, salt & pepper (breakfast-sausage style). Add peppers and onion.', 'Scramble eggs and whites softly in a separate pan.', 'Divide everything between tortillas, add cheese and salsa, roll tightly and wrap in foil.', 'Fridge 4 days or freezer 2 months. Reheat: microwave 2 min (unwrapped, in paper towel), then crisp in a pan.'] },
  { id: 'yogurt_parfait', name: 'Greek Yogurt Protein Parfait', cat: 'breakfast', emoji: '🍨', yield: 1, storage: 'fridge', time: 5,
    tags: ['No-cook'],
    ing: [['greek_yogurt', 250], ['whey', 15], ['granola', 30], ['berries', 100], ['honey', 7]],
    steps: ['Stir the whey into the yogurt until smooth.', 'Layer yogurt, berries and granola in a bowl or jar.', 'Drizzle with honey. (Keep granola separate if prepping ahead.)'] },
  { id: 'egg_bites', name: 'Cottage Cheese Egg Bites + English Muffin', cat: 'breakfast', emoji: '🧁', yield: 3, storage: 'fridge', time: 30,
    tags: ['Meal prep', 'Starbucks-style'],
    ing: [['egg', 6], ['egg_whites', 300], ['cottage', 250], ['cheese_shred', 60], ['spinach', 60], ['bell_pepper', 100], ['english_muffin', 3]],
    steps: ['Heat oven to 325°F. Blend eggs, whites and cottage cheese until very smooth.', 'Divide chopped spinach, pepper and cheese into 12 greased muffin cups; pour egg mixture over.', 'Place the tin inside a larger pan with 1 in of hot water; bake 25–30 min until just set.', 'Serve 4 bites with a toasted English muffin. Keeps 4 days refrigerated.'] },
  { id: 'cottage_bowl', name: 'Cottage Cheese Power Bowl', cat: 'breakfast', emoji: '🍌', yield: 1, storage: 'fresh', time: 3,
    tags: ['No-cook', '3 minutes'],
    ing: [['cottage', 300], ['banana', 1], ['pb', 16]],
    steps: ['Spoon cottage cheese into a bowl.', 'Top with sliced banana and a tablespoon of peanut butter.', 'Finish with cinnamon.'] },
  { id: 'breakfast_sandwiches', name: 'Freezer Breakfast Sandwiches', cat: 'breakfast', emoji: '🥪', yield: 4, storage: 'freezer', time: 25,
    tags: ['Meal prep', 'Freezes 1 month'],
    ing: [['english_muffin', 4], ['egg', 4], ['egg_whites', 400], ['canadian_bacon', 224], ['cheese_shred', 60]],
    steps: ['Heat oven to 350°F. Whisk eggs and whites; pour into a greased 9×13 pan and bake 15 min until set. Cut into 4.', 'Warm Canadian bacon in a skillet.', 'Stack muffin, egg square, Canadian bacon and cheese.', 'Wrap each in foil or parchment. Reheat from frozen: microwave 1.5–2 min.'] },

  /* ---------------- LUNCH ---------------- */
  { id: 'burrito_bowls', name: 'Chicken Burrito Bowls', cat: 'lunch', emoji: '🌮', yield: 4, storage: 'fridge', time: 35,
    tags: ['Meal prep', 'Top-rated'],
    ing: [['chicken_breast', 800], ['rice', 600], ['black_beans', 300], ['corn', 200], ['salsa', 240], ['cheese_shred', 60], ['romaine', 200]],
    steps: ['Season chicken with chili powder, cumin, garlic, lime, salt; grill or bake at 425°F for ~20 min to 165°F.', 'Cook rice (≈200 g dry) with lime juice and cilantro.', 'Warm beans and corn.', 'Divide rice, beans, corn and sliced chicken into 4 containers. Add salsa, cheese and lettuce when serving.'] },
  { id: 'turkey_chili', name: 'Turkey & Bean Chili', cat: 'lunch', emoji: '🌶️', yield: 4, storage: 'freezer', time: 45,
    tags: ['Meal prep', 'Freezes 3 months'],
    ing: [['turkey_937', 900], ['kidney_beans', 400], ['crushed_tomatoes', 800], ['onion', 200], ['bell_pepper', 200], ['greek_yogurt', 200], ['cheese_shred', 40]],
    steps: ['Brown turkey in a large pot; add diced onion and pepper and cook 5 min.', 'Stir in 2 tbsp chili powder, 2 tsp cumin, 1 tsp smoked paprika, garlic, salt.', 'Add crushed tomatoes and beans; simmer 25–30 min.', 'Portion into 4. Serve topped with Greek yogurt (sour cream swap) and cheese.'] },
  { id: 'greek_chicken', name: 'Greek Chicken Bowls', cat: 'lunch', emoji: '🥙', yield: 4, storage: 'fridge', time: 35,
    tags: ['Meal prep', 'Mediterranean'],
    ing: [['chicken_breast', 800], ['olive_oil', 15], ['quinoa', 600], ['cucumber', 300], ['cherry_tomato', 300], ['onion', 80], ['feta', 60], ['greek_yogurt', 250]],
    steps: ['Marinate chicken in olive oil, lemon juice, garlic, oregano, salt & pepper (30 min+).', 'Bake at 425°F 18–22 min or grill; slice.', 'Cook quinoa (≈220 g dry). Make tzatziki: Greek yogurt + grated cucumber, garlic, dill, lemon.', 'Divide quinoa, chicken, cucumber, tomatoes and red onion; top with feta and tzatziki.'] },
  { id: 'tuna_wrap', name: 'Tuna Salad Wrap', cat: 'lunch', emoji: '🥫', yield: 1, storage: 'fresh', time: 8,
    tags: ['Quick', 'Budget'],
    ing: [['tuna_can', 150], ['greek_yogurt', 40], ['light_mayo', 15], ['celery', 30], ['tortilla_lg', 1], ['romaine', 30], ['cherry_tomato', 50]],
    steps: ['Mix drained tuna with Greek yogurt, light mayo, diced celery, mustard, salt & pepper.', 'Lay lettuce and tomato on the tortilla, add tuna salad.', 'Roll tightly and slice in half.'] },
  { id: 'poke_bowl', name: 'Ahi Poke Bowl', cat: 'lunch', emoji: '🍣', yield: 1, storage: 'fresh', time: 15,
    tags: ['Fresh', 'Buy sushi-grade'],
    ing: [['ahi', 150], ['soy_sauce', 15], ['sesame_oil', 3], ['sushi_rice', 180], ['edamame', 60], ['cucumber', 60], ['avocado', 50], ['light_mayo', 10], ['sriracha', 5]],
    steps: ['Cube the ahi and toss with soy sauce, sesame oil, green onion and sesame seeds; chill 10 min.', 'Add warm sushi rice to a bowl.', 'Top with tuna, edamame, cucumber and avocado.', 'Mix light mayo + sriracha and drizzle. Eat the same day.'] },
  { id: 'caesar_wrap', name: 'Chicken Caesar Wrap', cat: 'lunch', emoji: '🥬', yield: 1, storage: 'fresh', time: 15,
    tags: ['Quick'],
    ing: [['chicken_breast', 170], ['romaine', 60], ['parmesan', 10], ['greek_yogurt', 40], ['tortilla_lg', 1]],
    steps: ['Season and pan-sear or grill the chicken (~6 min per side); slice.', 'Make dressing: Greek yogurt, lemon, Dijon, garlic, half the parmesan, pepper.', 'Toss chopped romaine with dressing, add chicken and remaining parmesan to the tortilla, and roll.'] },
  { id: 'beef_broccoli', name: 'Beef & Broccoli Rice Bowls', cat: 'lunch', emoji: '🥦', yield: 4, storage: 'fridge', time: 30,
    tags: ['Meal prep', 'Takeout copycat'],
    ing: [['sirloin', 800], ['broccoli', 600], ['rice', 600], ['soy_sauce', 60], ['honey', 30], ['cornstarch', 10], ['sesame_oil', 10]],
    steps: ['Slice beef thin against the grain; toss with half the cornstarch.', 'Whisk sauce: soy, honey, remaining cornstarch, garlic, ginger, ½ cup water.', 'Sear beef in sesame oil in batches; set aside. Steam-fry broccoli 3–4 min.', 'Return beef, add sauce and simmer 1 min until glossy. Serve over rice (≈200 g dry).'] },

  /* ---------------- DINNER ---------------- */
  { id: 'steak_potato', name: 'Steak, Sweet Potato & Green Beans', cat: 'dinner', emoji: '🥩', yield: 1, storage: 'fresh', time: 30,
    tags: ['Classic'],
    ing: [['sirloin', 225], ['sweet_potato', 250], ['green_beans', 150], ['olive_oil', 5]],
    steps: ['Cube the sweet potato and air-fry or roast at 425°F for 20–25 min.', 'Pat the steak dry, season well, and sear in a hot pan 3–4 min per side (130–135°F for medium-rare). Rest 5 min.', 'Sauté green beans in the olive oil with garlic, 4–5 min.'] },
  { id: 'fajitas', name: 'Sheet-Pan Chicken Fajitas', cat: 'dinner', emoji: '🫑', yield: 3, storage: 'fridge', time: 30,
    tags: ['Meal prep', 'One pan'],
    ing: [['chicken_breast', 700], ['bell_pepper', 450], ['onion', 200], ['olive_oil', 15], ['tortilla_sm', 6], ['salsa', 150], ['greek_yogurt', 150], ['avocado', 60]],
    steps: ['Heat oven to 425°F. Slice chicken, peppers and onion into strips.', 'Toss with olive oil and fajita seasoning (chili powder, cumin, paprika, garlic, salt).', 'Spread on a sheet pan and roast 20–22 min, broiling the last 2 min.', 'Serve 2 tortillas per portion with salsa, Greek yogurt and avocado.'] },
  { id: 'bolognese', name: 'Protein Pasta Bolognese', cat: 'dinner', emoji: '🍝', yield: 4, storage: 'freezer', time: 35,
    tags: ['Meal prep', 'Freezes 3 months'],
    ing: [['protein_pasta', 340], ['beef_937', 680], ['marinara', 700], ['onion', 150], ['spinach', 100], ['parmesan', 40]],
    steps: ['Cook the pasta 1 min short of the package time.', 'Brown beef with diced onion and garlic; drain if needed.', 'Add marinara and spinach; simmer 10 min.', 'Toss with pasta and portion into 4. Top with parmesan when serving.'] },
  { id: 'teriyaki_stirfry', name: 'Teriyaki Chicken Stir-Fry', cat: 'dinner', emoji: '🍚', yield: 3, storage: 'fridge', time: 25,
    tags: ['Meal prep', 'Top-rated'],
    ing: [['chicken_breast', 700], ['stir_fry_veg', 600], ['rice', 480], ['teriyaki', 90], ['sesame_oil', 10]],
    steps: ['Cube the chicken and sear in sesame oil over high heat until browned and cooked through.', 'Add frozen vegetables and cook 4–5 min.', 'Pour in teriyaki sauce and toss until glossy.', 'Serve over rice (≈160 g dry for 3 portions).'] },
  { id: 'sushi_night', name: 'Sushi Night (Rolls + Sashimi)', cat: 'dinner', emoji: '🍱', yield: 1, storage: 'fresh', time: 0,
    tags: ['Restaurant or homemade', 'Estimate'],
    ing: [['sushi_rice', 250], ['ahi', 120], ['salmon', 60], ['avocado', 30], ['nori', 2], ['cucumber', 40], ['soy_sauce', 15], ['edamame', 100]],
    steps: ['Order: 1 tuna roll + 1 salmon-avocado roll + 4 pc tuna sashimi + edamame.', 'Skip tempura, cream-cheese and spicy-mayo-heavy rolls to stay near these macros.', 'Homemade: 2 nori sheets, 250 g seasoned rice, sliced fish, cucumber and avocado.'] },
  { id: 'burger_bowl', name: 'Big Mac Burger Bowl + Wedges', cat: 'dinner', emoji: '🍔', yield: 1, storage: 'fresh', time: 25,
    tags: ['Comfort food'],
    ing: [['beef_937', 200], ['romaine', 100], ['cherry_tomato', 60], ['pickles', 30], ['onion', 20], ['cheese_shred', 20], ['light_mayo', 15], ['ketchup', 10], ['potato', 250], ['olive_oil', 5]],
    steps: ['Cut the potato into wedges, toss with the oil and seasoning; air-fry at 400°F ~20 min.', 'Brown the beef with salt, pepper and onion powder, breaking it up.', 'Mix "Mac sauce": light mayo, ketchup, chopped pickle, mustard, a pinch of paprika.', 'Build: lettuce, beef, cheese, tomato, pickles, onion; drizzle sauce. Wedges on the side.'] },
  { id: 'pork_tenderloin', name: 'Garlic-Herb Pork Tenderloin & Potatoes', cat: 'dinner', emoji: '🥔', yield: 3, storage: 'fridge', time: 40,
    tags: ['Meal prep', 'Sheet pan'],
    ing: [['pork_tenderloin', 700], ['potato', 750], ['asparagus', 450], ['olive_oil', 20]],
    steps: ['Heat oven to 425°F. Halve the baby potatoes, toss with half the oil, salt and rosemary; roast 15 min.', 'Rub pork with garlic, thyme, salt, pepper and the rest of the oil; add to the pan with asparagus.', 'Roast 18–22 min until pork hits 145°F. Rest 5 min and slice.'] },
  { id: 'honey_garlic_thighs', name: 'Honey-Garlic Chicken Thighs & Rice', cat: 'dinner', emoji: '🍗', yield: 3, storage: 'fridge', time: 35,
    tags: ['Meal prep'],
    ing: [['chicken_thigh', 750], ['rice', 480], ['broccoli', 450], ['honey', 30], ['soy_sauce', 45]],
    steps: ['Whisk honey, soy, minced garlic and a pinch of chili flakes.', 'Sear thighs 5 min per side, pour the sauce over and simmer until sticky and 175°F inside.', 'Steam broccoli; cook rice (≈160 g dry).', 'Portion into 3 containers.'] },

  /* ---------------- SNACKS ---------------- */
  { id: 'protein_shake', name: 'Whey Protein Shake', cat: 'snack', emoji: '🥤', yield: 1, storage: 'fresh', time: 1,
    tags: ['Post-workout'],
    ing: [['whey', 30], ['fairlife', 240]],
    steps: ['Shake or blend 1 scoop whey with cold milk (add ice for a thicker shake).'] },
  { id: 'protein_pudding', name: 'Chocolate Protein Pudding', cat: 'snack', emoji: '🍫', yield: 1, storage: 'fridge', time: 3,
    tags: ['Dessert-style'],
    ing: [['greek_yogurt', 200], ['whey', 15], ['cocoa', 5], ['pb2', 12]],
    steps: ['Stir whey, cocoa and PB2 into the yogurt until it turns thick and mousse-like.', 'Chill 10 min or eat right away.'] },
  { id: 'yogurt_berries', name: 'Greek Yogurt & Berries', cat: 'snack', emoji: '🫐', yield: 1, storage: 'fresh', time: 2,
    tags: ['No-cook'],
    ing: [['greek_yogurt', 200], ['berries', 80], ['honey', 5]],
    steps: ['Top yogurt with berries and a drizzle of honey.'] },
  { id: 'cottage_pineapple', name: 'Cottage Cheese & Pineapple', cat: 'snack', emoji: '🍍', yield: 1, storage: 'fresh', time: 2,
    tags: ['No-cook'],
    ing: [['cottage', 200], ['pineapple', 100]],
    steps: ['Spoon cottage cheese into a bowl and top with pineapple.'] },
  { id: 'jerky_apple', name: 'Beef Jerky & an Apple', cat: 'snack', emoji: '🍎', yield: 1, storage: 'fresh', time: 0,
    tags: ['On the go'],
    ing: [['jerky', 42], ['apple', 1]],
    steps: ['Grab 1.5 oz of jerky and an apple. Choose lower-sugar jerky when possible.'] },
  { id: 'turkey_rollups', name: 'Turkey & Cheese Roll-Ups', cat: 'snack', emoji: '🧀', yield: 1, storage: 'fresh', time: 3,
    tags: ['Low carb'],
    ing: [['deli_turkey', 85], ['string_cheese', 1], ['pickles', 30]],
    steps: ['Wrap slices of turkey around the string cheese (split in halves) and a pickle spear. Add mustard.'] },
  { id: 'boiled_eggs', name: 'Hard-Boiled Eggs & Carrots', cat: 'snack', emoji: '🥚', yield: 3, storage: 'fridge', time: 15,
    tags: ['Meal prep'],
    ing: [['egg', 6], ['carrots', 240]],
    steps: ['Boil eggs 10–11 min, then transfer to ice water. Peel and refrigerate (keeps 5 days).', 'Serve 2 eggs with baby carrots and everything-bagel seasoning.'] },
  { id: 'edamame_snack', name: 'Sea-Salt Edamame', cat: 'snack', emoji: '🫛', yield: 1, storage: 'fresh', time: 5,
    tags: ['Plant protein'],
    ing: [['edamame', 150]],
    steps: ['Microwave or steam frozen shelled edamame 3–4 min; season with flaky salt and chili flakes.'] },
  { id: 'rice_cakes_pb', name: 'Rice Cakes, PB & Banana', cat: 'snack', emoji: '🍘', yield: 1, storage: 'fresh', time: 2,
    tags: ['Pre-workout carbs'],
    ing: [['rice_cake', 2], ['pb', 16], ['banana', 0.5]],
    steps: ['Spread peanut butter over rice cakes and top with banana slices. Great 60–90 min before training.'] },
  { id: 'protein_bar', name: 'Protein Bar', cat: 'snack', emoji: '🍫', yield: 1, storage: 'fresh', time: 0, fixed: true,
    tags: ['Grab & go', 'Fixed portion'],
    ing: [['protein_bar', 1]],
    steps: ['Pick a bar with ~20 g protein and ≤ 220 kcal (Quest, Barebells, ONE, etc.).'] },

  /* ---------------- OPTIONAL (enabled by Food preferences) ---------------- */
  { id: 'salmon_rice', name: 'Garlic Salmon, Rice & Asparagus', cat: 'dinner', emoji: '🐟', yield: 1, storage: 'fresh', time: 20,
    tags: ['Omega-3'],
    ing: [['salmon_fillet', 170], ['rice', 180], ['asparagus', 150], ['soy_sauce', 10]],
    steps: ['Season salmon with garlic, lemon, salt & pepper; bake at 400°F 12–14 min (or air-fry 9–10 min).', 'Roast asparagus on the same pan for the last 8 min.', 'Serve over rice with a splash of soy sauce.'] },
  { id: 'shrimp_bowls', name: 'Cajun Shrimp Rice Bowls', cat: 'lunch', emoji: '🍤', yield: 3, storage: 'fridge', time: 20,
    tags: ['Meal prep', 'Lean'],
    ing: [['shrimp', 700], ['olive_oil', 15], ['rice', 540], ['bell_pepper', 300], ['corn', 150], ['salsa', 120]],
    steps: ['Toss shrimp with Cajun seasoning and half the oil.', 'Sauté peppers and corn in the remaining oil 4 min; push aside and cook shrimp 2 min per side.', 'Divide rice (≈180 g dry), veg and shrimp into 3 containers; top with salsa.'] },
  { id: 'tofu_teriyaki', name: 'Crispy Tofu Teriyaki Bowls', cat: 'dinner', emoji: '🥢', yield: 3, storage: 'fridge', time: 35,
    tags: ['Meal prep', 'Plant-based'],
    ing: [['tofu', 600], ['cornstarch', 15], ['sesame_oil', 10], ['edamame', 150], ['broccoli', 450], ['rice', 480], ['teriyaki', 90]],
    steps: ['Press tofu 15 min, cube, toss with cornstarch and air-fry at 400°F 15 min until crisp.', 'Stir-fry broccoli and edamame in sesame oil 4 min.', 'Toss tofu in teriyaki, serve over rice (≈160 g dry for 3 portions).'] }
];
const ING = {};
const RECIPES = [];
const RECIPE = {};
const MEAL_SLOTS = ['breakfast', 'lunch', 'dinner', 'snack1', 'snack2'];
const SLOT_LABEL = { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack1: 'Snack', snack2: 'Snack 2' };
const SLOT_CAT = { breakfast: 'breakfast', lunch: 'lunch', dinner: 'dinner', snack1: 'snack', snack2: 'snack' };


/* ---------- recipe links (verified pages for each built-in recipe) ---------- */
const RECIPE_LINKS = {
  overnight_oats: [{ title: "Protein Overnight Oats", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/protein-overnight-oats/" }, { title: "Protein Overnight Oats", site: "Well Plated", url: "https://www.wellplated.com/protein-oatmeal/" }],
  egg_white_omelette: [{ title: "Egg White Omelette", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/egg-white-omelette/" }, { title: "Egg White Omelette", site: "Cooking Classy", url: "https://www.cookingclassy.com/egg-white-omelette/" }],
  protein_pancakes: [{ title: "Blueberry Protein Pancakes", site: "Kodiak", url: "https://kodiakcakes.com/blogs/recipes/blueberry-protein-pancakes" }, { title: "5-Ingredient Protein Pancakes (40g Protein)", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/protein-pancakes/" }],
  breakfast_burritos: [{ title: "Breakfast Burritos with Turkey Sausage (Freezer-Friendly)", site: "Lovely Delites", url: "https://lovelydelites.com/breakfast-burritos-with-turkey-sausage-freezer-friendly/" }, { title: "Breakfast Burritos (Make-Ahead or Fresh)", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/breakfast-burritos/" }],
  yogurt_parfait: [{ title: "Fruit & Yogurt Parfait with Granola", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/yogurt-parfait/" }, { title: "Fruit and Yogurt Parfait", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/fruit-and-yogurt-parfait/" }],
  egg_bites: [{ title: "Easy High-Protein Cottage Cheese Egg Bites", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/cottage-cheese-egg-bites/" }, { title: "Starbucks Egg Bites Recipe (Copycat)", site: "The Kitchn", url: "https://www.thekitchn.com/egg-bites-starbucks-23761698" }],
  cottage_bowl: [{ title: "Peanut Butter & Banana Cottage Cheese Bowl", site: "The Schmidty Wife", url: "https://theschmidtywife.com/cottage-cheese-breakfast-bowls-peanut-butter-banana/" }, { title: "Cottage Cheese Breakfast Bowls (6 Ways)", site: "Budget Bytes", url: "https://www.budgetbytes.com/cottage-cheese-breakfast-bowls-6-ways/" }],
  breakfast_sandwiches: [{ title: "Make-Ahead Freezer Breakfast Sandwiches", site: "The Suburban Soapbox", url: "https://thesuburbansoapbox.com/make-ahead-freezer-breakfast-sandwiches/" }, { title: "Ultimate Freezer Breakfast Sandwiches", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/freezer-breakfast-sandwiches/" }],
  burrito_bowls: [{ title: "Burrito Bowl (Healthy Chipotle Copycat)", site: "Well Plated", url: "https://www.wellplated.com/chipotle-burrito-bowl/" }, { title: "Copycat Chipotle Chicken Burrito Bowl", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/naked-chicken-burritos/" }],
  turkey_chili: [{ title: "Easy Healthy Turkey Chili", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/turkey-chili/" }, { title: "Easy Healthy Turkey Chili", site: "Budget Bytes", url: "https://www.budgetbytes.com/turkey-chili/" }],
  greek_chicken: [{ title: "Chicken Tzatziki Bowls", site: "Skinnytaste", url: "https://www.skinnytaste.com/chicken-tzatziki-bowls/" }, { title: "Greek Bowls", site: "Well Plated", url: "https://www.wellplated.com/greek-bowls/" }],
  tuna_wrap: [{ title: "Tuna Wrap", site: "Budget Bytes", url: "https://www.budgetbytes.com/tuna-wrap/" }, { title: "Healthy Tuna Salad (High Protein)", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/tuna-salad/" }],
  poke_bowl: [{ title: "Ahi Tuna Poke Bowl", site: "Downshiftology", url: "https://downshiftology.com/recipes/ahi-tuna-poke-bowl/" }, { title: "Spicy Tuna Poke Bowl", site: "Skinnytaste", url: "https://www.skinnytaste.com/spicy-tuna-poke-bowls/" }],
  caesar_wrap: [{ title: "Chicken Caesar Wrap", site: "Well Plated", url: "https://www.wellplated.com/chicken-caesar-sandwich/" }, { title: "Chicken Caesar Wrap", site: "The Kitchn", url: "https://www.thekitchn.com/chicken-caesar-wrap-recipe-23783777" }],
  beef_broccoli: [{ title: "Broccoli Beef", site: "Well Plated", url: "https://www.wellplated.com/healthy-beef-and-broccoli/" }, { title: "Broccoli Beef", site: "Skinnytaste", url: "https://www.skinnytaste.com/broccoli-beef/" }],
  steak_potato: [{ title: "Sheet Pan Steak and Potatoes with Green Beans", site: "What Great Grandma Ate", url: "https://whatgreatgrandmaate.com/sheet-pan-steak-and-potatoes/" }, { title: "Steak and Sweet Potato Skillet", site: "Recipe Runner", url: "https://reciperunner.com/steak-and-sweet-potato-skillet/" }],
  fajitas: [{ title: "Easy Sheet Pan Chicken Fajitas", site: "Downshiftology", url: "https://downshiftology.com/recipes/sheet-pan-chicken-fajitas/" }, { title: "Sheet Pan Chicken Fajitas", site: "Budget Bytes", url: "https://www.budgetbytes.com/oven-fajitas/" }],
  bolognese: [{ title: "Pasta with Bolognese Sauce", site: "Skinnytaste", url: "https://www.skinnytaste.com/pasta-with-bolognese-sauce/" }, { title: "Spaghetti Meal Prep", site: "Budget Bytes", url: "https://www.budgetbytes.com/spaghetti-meal-prep/" }],
  teriyaki_stirfry: [{ title: "Teriyaki Chicken Stir Fry", site: "Well Plated", url: "https://www.wellplated.com/teriyaki-chicken-stir-fry/" }, { title: "Teriyaki Chicken Stir Fry", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/teriyaki-chicken-stir-fry/" }],
  sushi_night: [{ title: "Sushi Rolls (Hosomaki)", site: "Just One Cookbook", url: "https://www.justonecookbook.com/sushi-rolls/" }, { title: "Salmon Avocado Rolls", site: "RecipeTin Japan", url: "https://japan.recipetineats.com/salmon-avocado-rolls/" }],
  burger_bowl: [{ title: "Burger Bowls with Big Mac Sauce", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/burger-bowls/" }, { title: "Big Mac Salad Bowl (High Protein)", site: "Oh Snap Macros", url: "https://ohsnapmacros.com/big-mac-bowls/" }],
  pork_tenderloin: [{ title: "Sheet Pan Pork Tenderloin Dinner", site: "The Real Food Dietitians", url: "https://therealfooddietitians.com/sheet-pan-pork-tenderloin/" }, { title: "Herb Roasted Pork Tenderloin", site: "Budget Bytes", url: "https://www.budgetbytes.com/herb-roasted-pork-loin/" }],
  honey_garlic_thighs: [{ title: "Honey Garlic Chicken Thighs", site: "Gimme Delicious", url: "https://gimmedelicious.com/honey-garlic-chicken/" }, { title: "Instant Pot Honey Garlic Chicken Thighs", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/instant-pot-honey-garlic-chicken-thighs/" }],
  protein_shake: [{ title: "How to Make a Protein Shake", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/protein-shakes/" }, { title: "The 10 Best Protein Shake Recipes", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/best-protein-shakes/" }],
  protein_pudding: [{ title: "Chocolate Protein Pudding (45g Protein)", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/protein-pudding/" }, { title: "Chocolate Peanut Butter Greek Yogurt (PB2)", site: "Salad in a Jar", url: "https://saladinajar.com/recipes/snacks/chocolate-peanut-butter-greek-yogurt/" }],
  yogurt_berries: [{ title: "Yogurt Bowls (4 Ways)", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/yogurt-breakfast-bowls/" }, { title: "Mix-and-Match Greek Yogurt Parfaits", site: "Well Plated", url: "https://www.wellplated.com/greek-yogurt-parfait/" }],
  cottage_pineapple: [{ title: "Cottage Cheese with Pineapple", site: "TastyAZ", url: "https://www.tastyaz.com/cottage-cheese-with-pineapple/" }, { title: "Cottage Cheese Breakfast Bowls (6 Ways)", site: "Budget Bytes", url: "https://www.budgetbytes.com/cottage-cheese-breakfast-bowls-6-ways/" }],
  jerky_apple: [{ title: "High Protein Snacks", site: "Skinnytaste", url: "https://www.skinnytaste.com/high-protein-snacks/" }, { title: "30 Healthy High-Protein Snacks", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/high-protein-snacks/" }],
  turkey_rollups: [{ title: "Turkey, Cheese & Pickle Bites", site: "Health Beet", url: "https://healthbeet.org/turkey-cheese-and-pickle-bites/" }, { title: "Turkey Pickle Roll Ups", site: "Weelicious", url: "https://weelicious.com/turkey-pickle-roll-ups-recipe/" }],
  boiled_eggs: [{ title: "Easy-to-Peel Hard Boiled Eggs", site: "Downshiftology", url: "https://downshiftology.com/recipes/hard-boiled-eggs/" }, { title: "How to Make Hard Boiled Eggs", site: "Budget Bytes", url: "https://www.budgetbytes.com/how-to-make-hard-boiled-eggs/" }],
  edamame_snack: [{ title: "How to Cook Edamame (Fresh and Frozen)", site: "Just One Cookbook", url: "https://www.justonecookbook.com/edamame/" }, { title: "Easy Edamame", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/easy-edamame/" }],
  rice_cakes_pb: [{ title: "Rice Cakes with Peanut Butter and Banana", site: "Loaves and Dishes", url: "https://www.loavesanddishes.net/rice-cakes-with-peanut-butter-and-banana/" }, { title: "Rice Cakes with Peanut Butter and Banana", site: "Melanie Cooks", url: "https://www.melaniecooks.com/rice-cakes-with-peanut-butter-and-banana/49108/" }],
  protein_bar: [{ title: "The Best Protein Bars According to a Dietitian", site: "The Real Food Dietitians", url: "https://therealfooddietitians.com/best-protein-bars/" }, { title: "Easy Protein Bars", site: "Eating Bird Food", url: "https://www.eatingbirdfood.com/protein-bars/" }],
  salmon_rice: [{ title: "One-Pan Salmon and Asparagus", site: "Natasha's Kitchen", url: "https://natashaskitchen.com/one-pan-salmon-asparagus-recipe-video/" }, { title: "Sheet Pan Honey Glazed Salmon", site: "The Real Food Dietitians", url: "https://therealfooddietitians.com/sheet-pan-honey-glazed-salmon/" }],
  shrimp_bowls: [{ title: "Cajun Shrimp Bowl", site: "Deep South Dish", url: "https://www.deepsouthdish.com/2024/08/cajun-shrimp-bowl.html" }, { title: "Grilled Shrimp Meal Prep Bowls", site: "Fit Foodie Finds", url: "https://fitfoodiefinds.com/fresh-grilled-shrimp-meal-prep-bowls/" }],
  tofu_teriyaki: [{ title: "Teriyaki Tofu Bowls with Kimchi Mayo", site: "Pinch of Yum", url: "https://pinchofyum.com/teriyaki-tofu-bowls-with-kimchi-mayo" }, { title: "Crispy Teriyaki Tofu", site: "Two Peas & Their Pod", url: "https://www.twopeasandtheirpod.com/crispy-teriyaki-tofu/" }]
};
BASE_RECIPES.forEach(r => { r.links = (RECIPE_LINKS[r.id] || []).map(l => Object.assign({}, l)); });
